/**
 * Per-100g nutrition reference for the recipe ingredient vocabulary (task #115).
 *
 * WHY THIS EXISTS
 * The 957 recipes in `recipes` were generated by an LLM — both the ingredient lists and
 * the macros. The macros were never derived from the ingredients, which is why a user on
 * Browse Meals saw lists that don't match the numbers. This table lets us do it properly:
 * assign a quantity to every ingredient, then COMPUTE the macros from those quantities.
 *
 * CONVENTIONS — read before adding entries
 * - Values are per 100 g EDIBLE PORTION, using standard food-composition figures
 *   (USDA FoodData Central / McCance & Widdowson conventions).
 * - Grains, pasta, pulses and oats are DRY/UNCOOKED weight, which is what a recipe
 *   ingredient line means ("60g basmati rice"). Anything meant as cooked weight has
 *   `cooked: true` and uses cooked values. Getting this wrong is a ~3x calorie error, so
 *   it is the single most important field here.
 * - Meat and fish are RAW.
 * - `confidence: 'low'` marks a value worth a second look. `recompute.ts` refuses to
 *   auto-apply any recipe containing a low-confidence ingredient — it goes to review.
 * - kcal is stored as published, NOT recomputed from the macros. Small Atwater
 *   discrepancies are normal in real composition data; a validator checks the gap.
 */

export type Food = {
  /** kcal per 100 g */
  kcal: number;
  /** grams per 100 g */
  protein: number;
  carbs: number;
  fat: number;
  /** True when the figures are for the cooked food (default: raw / dry). */
  cooked?: boolean;
  confidence?: 'low';
  note?: string;
};

/**
 * Keys are normalised food names (lowercase, quantity stripped). Matching is done by
 * `normaliseFood()` in parse-seeds.ts, longest-key-first with word boundaries — so
 * "butter beans" never matches "butter".
 */
export const FOODS: Record<string, Food> = {
  // ── Meat & poultry (raw) ────────────────────────────────────────────────
  'chicken breast':       { kcal: 165, protein: 31,   carbs: 0,    fat: 3.6 },
  'chicken thigh':        { kcal: 209, protein: 26,   carbs: 0,    fat: 10.9 },
  'chicken thighs':       { kcal: 209, protein: 26,   carbs: 0,    fat: 10.9 },
  'turkey breast':        { kcal: 114, protein: 23.7, carbs: 0.1,  fat: 1.5, note: 'USDA Turkey breast, meat only, raw' },
  'turkey mince':         { kcal: 150, protein: 27,   carbs: 0,    fat: 4.5 },
  'beef mince':           { kcal: 250, protein: 26,   carbs: 0,    fat: 15,   note: '~15% fat' },
  'beef ribeye steak':    { kcal: 271, protein: 24,   carbs: 0,    fat: 19 },
  'sirloin steak':        { kcal: 210, protein: 27,   carbs: 0,    fat: 11 },
  'steak':                { kcal: 210, protein: 27,   carbs: 0,    fat: 11 },
  'lamb leg':             { kcal: 191, protein: 25,   carbs: 0,    fat: 10 },
  'pork tenderloin':      { kcal: 143, protein: 26,   carbs: 0,    fat: 3.5 },
  'pork belly':           { kcal: 518, protein: 9.3,  carbs: 0,    fat: 53 },
  'bacon':                { kcal: 250, protein: 20,   carbs: 0,    fat: 19,   note: 'smoked back, raw' },

  // ── Fish & seafood (raw) ────────────────────────────────────────────────
  'salmon fillet':        { kcal: 208, protein: 20,   carbs: 0,    fat: 13 },
  'haddock fillet':       { kcal: 74,  protein: 16.3, carbs: 0,    fat: 0.5, note: 'USDA Haddock, raw' },
  'cod fillet':           { kcal: 82,  protein: 18,   carbs: 0,    fat: 0.7 },
  'mackerel':             { kcal: 205, protein: 19,   carbs: 0,    fat: 14 },
  'tuna steak':           { kcal: 109, protein: 24.4, carbs: 0,    fat: 0.5, note: 'USDA Tuna, yellowfin, raw' },
  'king prawns':          { kcal: 85,  protein: 20.1, carbs: 0,    fat: 0.5, note: 'USDA Shrimp, raw' },
  'sardines':             { kcal: 208, protein: 25,   carbs: 0,    fat: 11.5 },

  // ── Eggs & dairy ────────────────────────────────────────────────────────
  'eggs':                 { kcal: 143, protein: 12.6, carbs: 0.7,  fat: 9.5 },
  'egg':                  { kcal: 143, protein: 12.6, carbs: 0.7,  fat: 9.5 },
  'whole eggs':           { kcal: 143, protein: 12.6, carbs: 0.7,  fat: 9.5 },
  'egg whites':           { kcal: 52,  protein: 11,   carbs: 0.7,  fat: 0.2 },
  '0% greek yogurt':      { kcal: 59,  protein: 10.3, carbs: 3.6,  fat: 0.4 },
  'greek yogurt':         { kcal: 97,  protein: 9,    carbs: 3.9,  fat: 5 },
  'greek yoghurt':        { kcal: 97,  protein: 9,    carbs: 3.9,  fat: 5 },
  'cottage cheese':       { kcal: 84,  protein: 11,   carbs: 4.3,  fat: 2.3, note: 'USDA Cottage cheese, lowfat 2%' },
  'crumbled feta':        { kcal: 264, protein: 14,   carbs: 4.1,  fat: 21 },
  'feta':                 { kcal: 264, protein: 14,   carbs: 4.1,  fat: 21 },
  'halloumi':             { kcal: 321, protein: 22,   carbs: 2.2,  fat: 25 },
  'paneer':               { kcal: 296, protein: 20,   carbs: 3.4,  fat: 22 },
  'parmesan':             { kcal: 431, protein: 38,   carbs: 4.1,  fat: 29 },
  'full-fat cream cheese':{ kcal: 342, protein: 6,    carbs: 4.1,  fat: 34 },
  'double cream':         { kcal: 449, protein: 1.7,  carbs: 2.7,  fat: 48 },
  'sour cream':           { kcal: 198, protein: 2.4,  carbs: 4.6,  fat: 19 },
  'unsalted butter':      { kcal: 717, protein: 0.9,  carbs: 0.1,  fat: 81 },
  'soya milk':            { kcal: 33,  protein: 3.3,  carbs: 1.8,  fat: 1.8 },
  'milk':                 { kcal: 42,  protein: 3.4,  carbs: 5,    fat: 1 },

  // ── Plant proteins ──────────────────────────────────────────────────────
  'firm tofu':            { kcal: 144, protein: 17,   carbs: 2.8,  fat: 8.7 },
  'tofu':                 { kcal: 144, protein: 17,   carbs: 2.8,  fat: 8.7 },
  // Silken is mostly water — roughly a third of firm. Must be keyed separately.
  'silken tofu':          { kcal: 55,  protein: 5.8,  carbs: 2,    fat: 2.7 },
  'tempeh':               { kcal: 192, protein: 20,   carbs: 7.6,  fat: 11 },
  'seitan':               { kcal: 141, protein: 25,   carbs: 4,    fat: 1.9 },
  'quorn mince':          { kcal: 94,  protein: 14.5, carbs: 4.5,  fat: 2 },
  'dry soya mince':       { kcal: 336, protein: 52,   carbs: 33,   fat: 1,   note: 'dry TVP' },
  'soya protein':         { kcal: 375, protein: 88,   carbs: 3,    fat: 1.5, note: 'isolate powder' },
  'pea protein':          { kcal: 375, protein: 80,   carbs: 5,    fat: 5 },
  'whey':                 { kcal: 400, protein: 80,   carbs: 8,    fat: 6 },
  'edamame':              { kcal: 121, protein: 12,   carbs: 8.9,  fat: 5.2 },

  // ── Pulses & beans ──────────────────────────────────────────────────────
  'butter beans':         { kcal: 79,  protein: 4.9,  carbs: 14.9, fat: 0.2, cooked: true, note: 'USDA Lima beans, canned' },
  'black beans':          { kcal: 132, protein: 8.9,  carbs: 24,   fat: 0.5, cooked: true },
  'chickpeas':            { kcal: 164, protein: 8.9,  carbs: 27,   fat: 2.6, cooked: true },
  'lentils':              { kcal: 116, protein: 9,    carbs: 20,   fat: 0.4, cooked: true },
  'baked beans':          { kcal: 94,  protein: 4.8,  carbs: 16,   fat: 0.4, cooked: true },
  'kidney beans':         { kcal: 127, protein: 8.7,  carbs: 23,   fat: 0.5, cooked: true },
  'peas':                 { kcal: 81,  protein: 5.4,  carbs: 14,   fat: 0.4 },

  // ── Grains, bread & pasta (DRY unless marked cooked) ────────────────────
  // Cooked, for the same reason as the grains above: portions run to 250 g, and 250 g
  // of dry oats is 948 kcal — inside recipes stating 379–609 kcal in total. The
  // generator applied one gram scale to every carb component, so they are prepared
  // weights throughout. Explicitly-dry lines ("90g dry pasta") keep dry values below.
  'rolled oats':          { kcal: 71,  protein: 2.5,  carbs: 12,   fat: 1.4, cooked: true },
  'oats':                 { kcal: 71,  protein: 2.5,  carbs: 12,   fat: 1.4, cooked: true },
  // COOKED weights. Established empirically, not assumed: the seeded amounts for these
  // run 40–250 g with a median of 150–160 g. 150 g of DRY rice is 534 kcal, which is
  // impossible as one component of a ~400 kcal meal; 150 g cooked is ~195 kcal, which is
  // an ordinary portion. Reading them as dry inflated every affected recipe by ~48%.
  'white basmati rice':   { kcal: 130, protein: 2.7,  carbs: 28,   fat: 0.3, cooked: true },
  'brown rice':           { kcal: 123, protein: 2.7,  carbs: 26,   fat: 1,   cooked: true },
  'rice':                 { kcal: 130, protein: 2.7,  carbs: 28,   fat: 0.3, cooked: true },
  'quinoa':               { kcal: 120, protein: 4.4,  carbs: 21,   fat: 1.9, cooked: true },
  'couscous':             { kcal: 112, protein: 3.8,  carbs: 23,   fat: 0.2, cooked: true },
  'bulgur wheat':         { kcal: 83,  protein: 3.1,  carbs: 19,   fat: 0.2, cooked: true },
  'wholewheat pasta':     { kcal: 159, protein: 5.8,  carbs: 31.5, fat: 1.5, cooked: true, note: 'USDA Pasta, whole grain, cooked' },
  'soba noodles':         { kcal: 99,  protein: 5.1,  carbs: 21,   fat: 0.1, cooked: true },
  'shirataki noodles':    { kcal: 10,  protein: 0.2,  carbs: 3,    fat: 0,   cooked: true },
  'wholegrain bread':     { kcal: 247, protein: 13,   carbs: 41,   fat: 3.4 },
  'rye bread':            { kcal: 259, protein: 8.5,  carbs: 48,   fat: 3.3 },
  'wholewheat tortilla wrap': { kcal: 293, protein: 9,  carbs: 47, fat: 7 },
  'rice cakes':           { kcal: 387, protein: 8.2,  carbs: 81,   fat: 2.8 },

  // ── Starchy vegetables ──────────────────────────────────────────────────
  'sweet potato':         { kcal: 86,  protein: 1.6,  carbs: 20,   fat: 0.1 },
  'white potato':         { kcal: 77,  protein: 2,    carbs: 17,   fat: 0.1 },
  'potato mash':          { kcal: 88,  protein: 2,    carbs: 15,   fat: 2.3, cooked: true },
  'celeriac mash':        { kcal: 52,  protein: 1.5,  carbs: 9,    fat: 1.2, cooked: true },
  'swede':                { kcal: 37,  protein: 1.1,  carbs: 8.6,  fat: 0.2 },
  'turnip':               { kcal: 28,  protein: 0.9,  carbs: 6.4,  fat: 0.1 },

  // ── Vegetables ──────────────────────────────────────────────────────────
  'baby spinach':         { kcal: 23,  protein: 2.9,  carbs: 3.6,  fat: 0.4 },
  'spinach':              { kcal: 23,  protein: 2.9,  carbs: 3.6,  fat: 0.4 },
  'kale':                 { kcal: 35,  protein: 2.9,  carbs: 4.4,  fat: 1.5, note: 'USDA Kale, raw' },
  'cherry tomatoes':      { kcal: 18,  protein: 0.9,  carbs: 3.9,  fat: 0.2 },
  'cucumber':             { kcal: 15,  protein: 0.7,  carbs: 3.6,  fat: 0.1 },
  'red onion':            { kcal: 40,  protein: 1.1,  carbs: 9.3,  fat: 0.1 },
  'onion':                { kcal: 40,  protein: 1.1,  carbs: 9.3,  fat: 0.1 },
  'spring onions':        { kcal: 32,  protein: 1.8,  carbs: 7.3,  fat: 0.2 },
  'mixed peppers':        { kcal: 26,  protein: 1,    carbs: 6,    fat: 0.3, note: 'USDA Peppers, sweet, red, raw' },
  'courgette':            { kcal: 17,  protein: 1.2,  carbs: 3.1,  fat: 0.3 },
  'zucchini':             { kcal: 17,  protein: 1.2,  carbs: 3.1,  fat: 0.3 },
  'courgette noodles':    { kcal: 17,  protein: 1.2,  carbs: 3.1,  fat: 0.3 },
  'cauliflower':          { kcal: 25,  protein: 1.9,  carbs: 5,    fat: 0.3 },
  'cauliflower rice':     { kcal: 25,  protein: 1.9,  carbs: 5,    fat: 0.3 },
  'tenderstem broccoli':  { kcal: 31,  protein: 2.6,  carbs: 6.3,  fat: 0.3, note: 'USDA Broccoli, raw' },
  'broccoli florets':     { kcal: 34,  protein: 2.8,  carbs: 6.6,  fat: 0.4 },
  'green beans':          { kcal: 31,  protein: 1.8,  carbs: 7,    fat: 0.1 },
  'asparagus tips':       { kcal: 20,  protein: 2.2,  carbs: 3.9,  fat: 0.1 },
  'chestnut mushrooms':   { kcal: 22,  protein: 3.1,  carbs: 3.3,  fat: 0.3 },
  'mushrooms':            { kcal: 22,  protein: 3.1,  carbs: 3.3,  fat: 0.3 },
  'carrots':              { kcal: 41,  protein: 0.9,  carbs: 9.6,  fat: 0.2 },
  'carrot':               { kcal: 41,  protein: 0.9,  carbs: 9.6,  fat: 0.2 },
  'cabbage':              { kcal: 25,  protein: 1.3,  carbs: 5.8,  fat: 0.1 },
  'red cabbage':          { kcal: 31,  protein: 1.4,  carbs: 7.4,  fat: 0.2 },
  'celery':               { kcal: 16,  protein: 0.7,  carbs: 3,    fat: 0.2 },
  'leeks':                { kcal: 61,  protein: 1.5,  carbs: 14,   fat: 0.3 },
  'mixed salad leaves':   { kcal: 17,  protein: 1.4,  carbs: 2.9,  fat: 0.2 },
  'rocket':               { kcal: 25,  protein: 2.6,  carbs: 3.7,  fat: 0.7 },
  'olives':               { kcal: 81,  protein: 1,    carbs: 5.6,  fat: 6.9, note: 'USDA Olives, ripe, canned' },

  // ── Fruit ───────────────────────────────────────────────────────────────
  'avocado':              { kcal: 160, protein: 2,    carbs: 8.5,  fat: 15 },
  'avocado slices':       { kcal: 160, protein: 2,    carbs: 8.5,  fat: 15 },
  'banana':               { kcal: 89,  protein: 1.1,  carbs: 23,   fat: 0.3 },
  'berries':              { kcal: 50,  protein: 0.8,  carbs: 11,   fat: 0.3 },
  'mixed berries':        { kcal: 50,  protein: 0.8,  carbs: 11,   fat: 0.3 },
  'mango':                { kcal: 60,  protein: 0.8,  carbs: 15,   fat: 0.4 },

  // ── Nuts, seeds & fats ──────────────────────────────────────────────────
  'almonds':              { kcal: 579, protein: 21,   carbs: 22,   fat: 50 },
  'walnuts':              { kcal: 654, protein: 15,   carbs: 14,   fat: 65 },
  'mixed nuts':           { kcal: 607, protein: 20,   carbs: 21,   fat: 54 },
  'natural peanut butter':{ kcal: 588, protein: 25,   carbs: 20,   fat: 50 },
  'peanut butter':        { kcal: 588, protein: 25,   carbs: 20,   fat: 50 },
  'tahini':               { kcal: 595, protein: 17,   carbs: 21,   fat: 54 },
  'chia seeds':           { kcal: 486, protein: 17,   carbs: 42,   fat: 31 },
  'hemp seeds':           { kcal: 553, protein: 32,   carbs: 8.7,  fat: 49 },
  'sunflower seeds':      { kcal: 584, protein: 21,   carbs: 20,   fat: 51 },
  'pumpkin seeds':        { kcal: 559, protein: 30,   carbs: 11,   fat: 49 },
  'sesame seeds':         { kcal: 573, protein: 18,   carbs: 23,   fat: 50 },
  'pine nuts':            { kcal: 673, protein: 14,   carbs: 13,   fat: 68 },
  'olive oil':            { kcal: 884, protein: 0,    carbs: 0,    fat: 100 },
  'extra virgin olive oil': { kcal: 884, protein: 0,  carbs: 0,    fat: 100 },
  'coconut oil':          { kcal: 892, protein: 0,    carbs: 0,    fat: 100 },
  'sesame oil':           { kcal: 884, protein: 0,    carbs: 0,    fat: 100 },

  // ── Condiments & sauces ─────────────────────────────────────────────────
  'soy sauce':            { kcal: 53,  protein: 8.1,  carbs: 4.9,  fat: 0.6 },
  'tamari':               { kcal: 60,  protein: 10.5, carbs: 5.6,  fat: 0.1 },
  'teriyaki glaze':       { kcal: 89,  protein: 1.7,  carbs: 19,   fat: 0 },
  'hoisin sauce':         { kcal: 220, protein: 3.3,  carbs: 44,   fat: 3.4 },
  'rice vinegar':         { kcal: 18,  protein: 0,    carbs: 0.5,  fat: 0 },
  'dijon mustard':        { kcal: 66,  protein: 4,    carbs: 5.8,  fat: 3.3 },
  'honey':                { kcal: 304, protein: 0.3,  carbs: 82,   fat: 0 },
  'chimichurri sauce':    { kcal: 300, protein: 1,    carbs: 4,    fat: 31, confidence: 'low', note: 'oil-based, varies widely' },
  'sesame-ginger dressing': { kcal: 250, protein: 1,  carbs: 12,   fat: 22, confidence: 'low' },
  'mirin':                { kcal: 258, protein: 0.2,  carbs: 43,   fat: 0 },

  // ── Added to close the coverage gap (see coverage.ts) ───────────────────
  'grated cheddar':       { kcal: 402, protein: 25,   carbs: 1.3,  fat: 33 },
  'cheddar':              { kcal: 402, protein: 25,   carbs: 1.3,  fat: 33 },
  'low-fat mozzarella':   { kcal: 254, protein: 24,   carbs: 2.8,  fat: 16 },
  'coconut cream':        { kcal: 330, protein: 3.6,  carbs: 6.6,  fat: 34 },
  'high-protein soya yogurt': { kcal: 68, protein: 6, carbs: 4,    fat: 2.9 },
  'soya yogurt':          { kcal: 55,  protein: 4,    carbs: 4.5,  fat: 2.2 },
  'tomato passata':       { kcal: 34,  protein: 1.5,  carbs: 6.5,  fat: 0.2 },
  'passata':              { kcal: 34,  protein: 1.5,  carbs: 6.5,  fat: 0.2 },
  'crushed tomatoes':     { kcal: 32,  protein: 1.6,  carbs: 7,    fat: 0.3 },
  'sun-dried tomatoes':   { kcal: 258, protein: 14,   carbs: 56,   fat: 3,   note: 'dry, not oil-packed' },
  'new potatoes':         { kcal: 77,  protein: 2,    carbs: 17,   fat: 0.1 },
  'diced potato':         { kcal: 77,  protein: 2,    carbs: 17,   fat: 0.1 },
  'jacket potato':        { kcal: 93,  protein: 2.5,  carbs: 21,   fat: 0.1 },
  'dry pasta':            { kcal: 371, protein: 13,   carbs: 75,   fat: 1.5 },
  'pasta':                { kcal: 371, protein: 13,   carbs: 75,   fat: 1.5 },
  'red pepper':           { kcal: 31,  protein: 1,    carbs: 6,    fat: 0.3 },
  'dry spaghetti':        { kcal: 371, protein: 13,   carbs: 75,   fat: 1.5 },
  'whole wheat pasta':    { kcal: 348, protein: 14,   carbs: 71,   fat: 2.5 },
  'glass noodles':        { kcal: 351, protein: 0.1,  carbs: 86,   fat: 0.1 },
  'noodles':              { kcal: 338, protein: 11,   carbs: 71,   fat: 1.4 },
  'pearl barley':         { kcal: 123, protein: 2.3,  carbs: 28,   fat: 0.4, cooked: true, note: 'appears in soup, i.e. cooked' },
  'oat flour':            { kcal: 404, protein: 15,   carbs: 66,   fat: 9.1 },
  'gram (chickpea) flour':{ kcal: 387, protein: 22,   carbs: 58,   fat: 6.7 },
  'cooked basmati':       { kcal: 130, protein: 2.7,  carbs: 28,   fat: 0.3, cooked: true },
  'wholemeal bread':      { kcal: 247, protein: 13,   carbs: 41,   fat: 3.4 },
  'wholemeal toast':      { kcal: 247, protein: 13,   carbs: 41,   fat: 3.4 },
  'wholemeal wrap':       { kcal: 293, protein: 9,    carbs: 47,   fat: 7 },
  'wholemeal pitta':      { kcal: 266, protein: 9.8,  carbs: 53,   fat: 1.6 },
  'sourdough':            { kcal: 260, protein: 9,    carbs: 51,   fat: 1.8 },
  'plain bagel':          { kcal: 275, protein: 11,   carbs: 53,   fat: 1.7 },
  'granola':              { kcal: 471, protein: 10,   carbs: 64,   fat: 20 },
  'low-fat granola':      { kcal: 380, protein: 9,    carbs: 70,   fat: 6 },
  'crackers':             { kcal: 431, protein: 9,    carbs: 71,   fat: 12 },
  'pretzels':             { kcal: 380, protein: 10,   carbs: 80,   fat: 3 },
  'hummus':               { kcal: 166, protein: 7.9,  carbs: 14,   fat: 9.6 },
  'high-protein hummus':  { kcal: 180, protein: 12,   carbs: 13,   fat: 9 },
  'quorn pieces':         { kcal: 106, protein: 15,   carbs: 4.5,  fat: 3 },
  'quorn fillets':        { kcal: 106, protein: 15,   carbs: 4.5,  fat: 3 },
  'rehydrated soya mince':{ kcal: 105, protein: 16,   carbs: 5,    fat: 0.5, cooked: true },
  'turkey rasher':        { kcal: 110, protein: 21,   carbs: 1,    fat: 2.5 },
  'lean beef strips':     { kcal: 137, protein: 22,   carbs: 0,    fat: 5,   note: '5% fat' },
  'shrimp':               { kcal: 85,  protein: 20.1, carbs: 0,    fat: 0.5, note: 'USDA Shrimp, raw' },
  'cod loin':             { kcal: 82,  protein: 18,   carbs: 0,    fat: 0.7 },
  'smoked haddock':       { kcal: 90,  protein: 20,   carbs: 0,    fat: 0.6, note: 'smoked; cured, denser than raw' },
  'white beans':          { kcal: 139, protein: 9.7,  carbs: 25,   fat: 0.4, cooked: true },
  'vanilla protein':      { kcal: 375, protein: 80,   carbs: 6,    fat: 4 },
  'vanilla protein powder': { kcal: 375, protein: 80, carbs: 6,    fat: 4 },
  'maple syrup':          { kcal: 260, protein: 0,    carbs: 67,   fat: 0.1 },
  'light maple syrup':    { kcal: 160, protein: 0,    carbs: 40,   fat: 0 },
  'syrup':                { kcal: 260, protein: 0,    carbs: 67,   fat: 0.1 },
  'light syrup':          { kcal: 160, protein: 0,    carbs: 40,   fat: 0 },
  'jam':                  { kcal: 258, protein: 0.4,  carbs: 64,   fat: 0.1 },
  'raisins':              { kcal: 299, protein: 3.1,  carbs: 79,   fat: 0.5 },
  'dried apricots':       { kcal: 241, protein: 3.4,  carbs: 63,   fat: 0.5 },
  'pomegranate seeds':    { kcal: 83,  protein: 1.7,  carbs: 19,   fat: 1.2 },
  'apple':                { kcal: 52,  protein: 0.3,  carbs: 14,   fat: 0.2 },
  'kiwi':                 { kcal: 61,  protein: 1.1,  carbs: 15,   fat: 0.5 },
  'bell pepper':          { kcal: 31,  protein: 1,    carbs: 6,    fat: 0.3 },
  'bell peppers':         { kcal: 31,  protein: 1,    carbs: 6,    fat: 0.3 },
  'lettuce':              { kcal: 15,  protein: 1.4,  carbs: 2.9,  fat: 0.2 },
  'butter lettuce':       { kcal: 13,  protein: 1.4,  carbs: 2.2,  fat: 0.2 },
  'pak choi':             { kcal: 13,  protein: 1.5,  carbs: 2.2,  fat: 0.2 },
  'radish':               { kcal: 16,  protein: 0.7,  carbs: 3.4,  fat: 0.1 },
  'corn':                 { kcal: 86,  protein: 3.3,  carbs: 19,   fat: 1.4 },
  'corn tortillas':       { kcal: 218, protein: 5.7,  carbs: 45,   fat: 2.9 },
  'stir-fry vegetables':  { kcal: 35,  protein: 2,    carbs: 6,    fat: 0.4 },
  'roasted veg':          { kcal: 60,  protein: 1.8,  carbs: 8,    fat: 2.5, confidence: 'low', note: 'oil content unknown' },
  'broccoli':             { kcal: 34,  protein: 2.8,  carbs: 6.6,  fat: 0.4 },
  'asparagus':            { kcal: 20,  protein: 2.2,  carbs: 3.9,  fat: 0.1 },
  'leek':                 { kcal: 61,  protein: 1.5,  carbs: 14,   fat: 0.3 },
  'capers':               { kcal: 23,  protein: 2.4,  carbs: 4.9,  fat: 0.9 },
  'miso paste':           { kcal: 199, protein: 12,   carbs: 26,   fat: 6 },
  'white miso paste':     { kcal: 199, protein: 12,   carbs: 26,   fat: 6 },
  'salsa':                { kcal: 36,  protein: 1.5,  carbs: 7,    fat: 0.2 },
  'oyster sauce':         { kcal: 51,  protein: 1.4,  carbs: 11,   fat: 0.3 },
  'sriracha':             { kcal: 93,  protein: 1.9,  carbs: 19,   fat: 0.9 },
  'anchovy paste':        { kcal: 190, protein: 19,   carbs: 0,    fat: 12 },
  'flaxseed':             { kcal: 534, protein: 18,   carbs: 29,   fat: 42 },
  'chipotle in adobo':    { kcal: 65,  protein: 2,    carbs: 13,   fat: 1.5, confidence: 'low' },
  'dukkah':               { kcal: 550, protein: 18,   carbs: 20,   fat: 45, confidence: 'low' },
  'nori':                 { kcal: 35,  protein: 5.8,  carbs: 5.1,  fat: 0.3 },
  'dried wakame seaweed': { kcal: 45,  protein: 3,    carbs: 9,    fat: 0.6 },
  'chicken stock':        { kcal: 4,   protein: 0.5,  carbs: 0.4,  fat: 0.1 },
  'veg stock':            { kcal: 4,   protein: 0.2,  carbs: 0.7,  fat: 0.1 },
  'low-salt stock':       { kcal: 4,   protein: 0.3,  carbs: 0.5,  fat: 0.1 },
  'dashi':                { kcal: 5,   protein: 0.8,  carbs: 0.4,  fat: 0 },
  'gravy':                { kcal: 25,  protein: 0.6,  carbs: 4,    fat: 0.8 },
  'veg gravy':            { kcal: 25,  protein: 0.6,  carbs: 4,    fat: 0.8 },
  'tikka marinade':       { kcal: 120, protein: 3,    carbs: 10,   fat: 7,  confidence: 'low' },
  'tikka sauce':          { kcal: 120, protein: 3,    carbs: 10,   fat: 7,  confidence: 'low' },
  'mustard-herb glaze':   { kcal: 100, protein: 2,    carbs: 10,   fat: 5,  confidence: 'low' },
  'tomato & spice base':  { kcal: 45,  protein: 1.5,  carbs: 8,    fat: 1,  confidence: 'low' },
  'seeds':                { kcal: 570, protein: 22,   carbs: 18,   fat: 48 },

  // Tinned tuna — the packing medium changes this enormously, so both are explicit.
  // Without them "tinned tuna in olive oil" resolved to olive oil at 884 kcal/100g.
  'tinned tuna in olive oil':   { kcal: 189, protein: 25, carbs: 0, fat: 10, note: 'drained' },
  'tin tuna in spring water':   { kcal: 108, protein: 25, carbs: 0, fat: 0.8, note: 'drained' },
  'tuna in spring water':       { kcal: 108, protein: 25, carbs: 0, fat: 0.8 },
  'tinned tuna':                { kcal: 108, protein: 25, carbs: 0, fat: 0.8 },
  'tuna':                       { kcal: 108, protein: 25, carbs: 0, fat: 0.8 },

  // ── Composite seasoning lines emitted verbatim by the recipe generator ──
  // Priced as whole lines (exact-match in matchFood) with a realistic total weight in
  // portions.ts. Resolving these to a single component mispriced them badly: matching
  // only "sesame oil" ignored the soy sauce, and vice versa.
  'soy sauce, ginger and a splash of sesame oil':
    { kcal: 260, protein: 3.5, carbs: 3,  fat: 26, note: '~1 tbsp soy + 1 tsp sesame oil per line' },
  'tamari (gluten-free soy), ginger and a splash of sesame oil':
    { kcal: 260, protein: 4,   carbs: 3,  fat: 26 },
  'teriyaki glaze and toasted sesame seeds':
    { kcal: 210, protein: 4,   carbs: 26, fat: 10 },
  'fresh thyme, cracked black pepper and a splash of double cream':
    { kcal: 380, protein: 1.6, carbs: 3,  fat: 40 },
  'tamari (gluten-free soy), ginger and spring onion':
    { kcal: 55,  protein: 6,   carbs: 6,  fat: 0.4 },
  'tamari (gluten-free soy), ginger and mirin':
    { kcal: 120, protein: 4,   carbs: 24, fat: 0.2 },
  'oregano, basil and a squeeze of lemon':
    { kcal: 40,  protein: 2,   carbs: 8,  fat: 0.8 },
  'sesame':               { kcal: 573, protein: 18,   carbs: 23,   fat: 50 },
  'granulated sweetener': { kcal: 0,   protein: 0,    carbs: 0,    fat: 0 },

  // ── Negligible: herbs, spices, aromatics, water ─────────────────────────
  // Present so they resolve rather than flagging a recipe for review. Their
  // contribution at realistic amounts rounds to zero.
  'salt and black pepper': { kcal: 0, protein: 0, carbs: 0, fat: 0 },
  'salt & pepper':         { kcal: 0, protein: 0, carbs: 0, fat: 0 },
  'black pepper':          { kcal: 0, protein: 0, carbs: 0, fat: 0 },
  'water':                 { kcal: 0, protein: 0, carbs: 0, fat: 0 },
  'garlic':                { kcal: 149, protein: 6.4, carbs: 33,  fat: 0.5 },
  'ginger':                { kcal: 80,  protein: 1.8, carbs: 18,  fat: 0.8 },
  'lemon':                 { kcal: 29,  protein: 1.1, carbs: 9.3, fat: 0.3 },
  'lemon juice':           { kcal: 22,  protein: 0.4, carbs: 6.9, fat: 0.2 },
  'lime':                  { kcal: 30,  protein: 0.7, carbs: 11,  fat: 0.2 },
  'coriander':             { kcal: 23,  protein: 2.1, carbs: 3.7, fat: 0.5 },
  'parsley':               { kcal: 36,  protein: 3,   carbs: 6.3, fat: 0.8 },
  'basil':                 { kcal: 23,  protein: 3.2, carbs: 2.7, fat: 0.6 },
  'dill':                  { kcal: 43,  protein: 3.5, carbs: 7,   fat: 1.1 },
  'chilli flakes':         { kcal: 318, protein: 12,  carbs: 57,  fat: 17 },
  'smoked paprika':        { kcal: 282, protein: 14,  carbs: 54,  fat: 13 },
  'cumin':                 { kcal: 375, protein: 18,  carbs: 44,  fat: 22 },
  'cinnamon':              { kcal: 247, protein: 4,   carbs: 81,  fat: 1.2 },
  'oregano':               { kcal: 265, protein: 9,   carbs: 69,  fat: 4.3 },
  'chives':                { kcal: 30,  protein: 3.3, carbs: 4.4, fat: 0.7 },
  'mint':                  { kcal: 44,  protein: 3.3, carbs: 8.4, fat: 0.7 },
  'fresh thyme':           { kcal: 101, protein: 5.6, carbs: 24,  fat: 1.7 },
  'bay leaf':              { kcal: 0,   protein: 0,   carbs: 0,   fat: 0 },
  'chilli':                { kcal: 40,  protein: 1.9, carbs: 9,   fat: 0.4 },
  'jalapeño':              { kcal: 29,  protein: 0.9, carbs: 6.5, fat: 0.4 },
  'paprika':               { kcal: 282, protein: 14,  carbs: 54,  fat: 13 },
  'herbs de provence':     { kcal: 265, protein: 9,   carbs: 69,  fat: 4.3 },
  'herbs':                 { kcal: 265, protein: 9,   carbs: 69,  fat: 4.3 },
  'sea salt':              { kcal: 0,   protein: 0,   carbs: 0,   fat: 0 },
  'flaky sea salt':        { kcal: 0,   protein: 0,   carbs: 0,   fat: 0 },
  'turmeric & black salt': { kcal: 0,   protein: 0,   carbs: 0,   fat: 0 },
  'soy-free seasoning':    { kcal: 0,   protein: 0,   carbs: 0,   fat: 0 },
  'everything bagel seasoning': { kcal: 0, protein: 0, carbs: 0, fat: 0 },
  'baking powder':         { kcal: 0,   protein: 0,   carbs: 0,   fat: 0 },
  'vanilla':               { kcal: 0,   protein: 0,   carbs: 0,   fat: 0 },
  'ice':                   { kcal: 0,   protein: 0,   carbs: 0,   fat: 0 },
};

/**
 * Foods where published kcal legitimately disagrees with a naive Atwater sum:
 *  - high-fibre / high-water plants: published kcal excludes indigestible fibre,
 *    while 4 kcal/g over total carbohydrate counts it
 *  - mirin: ~8% ABV, and alcohol's 7 kcal/g isn't in the P/C/F sum at all
 * Exempting them is not hand-waving — it's why the check can stay strict elsewhere.
 */
const ATWATER_EXEMPT = new Set([
  'baby spinach', 'spinach', 'asparagus tips', 'chestnut mushrooms', 'mushrooms',
  'rocket', 'basil', 'lemon', 'lemon juice', 'lime', 'chilli flakes',
  'smoked paprika', 'cumin', 'cinnamon', 'garlic', 'ginger', 'coriander',
  'parsley', 'dill', 'mirin',
  // Dried herbs/spices and high-fibre plants — same fibre effect as above.
  'oregano', 'herbs', 'herbs de provence', 'fresh thyme', 'paprika', 'chives',
  'mint', 'chilli', 'jalapeño', 'sun-dried tomatoes', 'corn', 'nori',
  'dried wakame seaweed', 'capers', 'rehydrated soya mince', 'pomegranate seeds',
]);

/**
 * Sanity check: for calorie-dense foods, published kcal should track its own Atwater
 * sum. Catches a mistyped macro — the failure mode that would silently corrupt every
 * recipe using that ingredient.
 */
export function validateTable(): string[] {
  const problems: string[] = [];
  for (const [name, f] of Object.entries(FOODS)) {
    if (ATWATER_EXEMPT.has(name)) continue;
    const atwater = f.protein * 4 + f.carbs * 4 + f.fat * 9;
    if (f.kcal === 0 && atwater === 0) continue;
    if (f.kcal < 60) continue; // fibre/water dominate; ratio is meaningless here
    const delta = Math.abs(atwater - f.kcal) / Math.max(f.kcal, 1);
    if (delta > 0.15) {
      problems.push(
        `${name}: kcal ${f.kcal} vs Atwater ${atwater.toFixed(0)} (${(delta * 100).toFixed(0)}% apart)`,
      );
    }
  }
  return problems;
}
