"""Emit the two migrations: schema change + seed, from import_ready/payload.json."""
import json, os, sys

S = sys.argv[1] if len(sys.argv) > 1 else os.path.dirname(os.path.abspath(__file__))
MIG = "/Users/vanessa/hitt-app/supabase/migrations"
p = json.load(open(f"{S}/import_ready/payload.json"))
recipes, ingredients, steps = p["recipes"], p["ingredients"], p["steps"]

def q(v):
    if v is None: return "NULL"
    if isinstance(v, bool): return "TRUE" if v else "FALSE"
    if isinstance(v, (int, float)): return str(v)
    return "'" + str(v).replace("'", "''") + "'"

def arr(vals):
    if not vals: return "'{}'"
    return "ARRAY[" + ", ".join(q(v) for v in vals) + "]::TEXT[]"

# ------------------------------------------------------------------ schema
schema = f"""-- Recipes: meal-type categorisation + the owner pack's richer nutrition fields.
--
-- The owner's direction is to categorise by TYPE OF MEAL rather than by goal, for
-- browse variety. That frees `category` to hold a dish type (salad, curry, overnight_oats,
-- ...) and moves the goal axis into its own `goals` array — ai-coach still selects owner
-- recipes by goal, so the data cannot simply be dropped.

BEGIN;

-- 1. Two new meal slots for the pack's Desserts and Healthy Cheat Meals.
ALTER TABLE public.recipes DROP CONSTRAINT IF EXISTS recipes_meal_type_check;
ALTER TABLE public.recipes
  ADD CONSTRAINT recipes_meal_type_check CHECK (meal_type IN (
    'breakfast', 'lunch', 'dinner', 'snack',
    'pre_workout', 'post_workout', 'recovery',
    'dessert', 'cheat_meal'
  ));

-- 2. Stable external key from the owner's drop (BRK-001, DIN-224, ...). Makes the seed
--    re-runnable without touching the 927 pre-existing owner rows, which have none.
ALTER TABLE public.recipes ADD COLUMN IF NOT EXISTS external_id TEXT;
CREATE UNIQUE INDEX IF NOT EXISTS recipes_external_id_key
  ON public.recipes (external_id) WHERE external_id IS NOT NULL;

-- 3. Goal axis, now that `category` carries the dish type.
ALTER TABLE public.recipes ADD COLUMN IF NOT EXISTS goals TEXT[] NOT NULL DEFAULT '{{}}';
CREATE INDEX IF NOT EXISTS recipes_goals_idx ON public.recipes USING GIN (goals);

-- 4. Nutrition + serving detail the pack supplies and we currently have nowhere to put.
ALTER TABLE public.recipes
  ADD COLUMN IF NOT EXISTS fibre_g          NUMERIC(6,1),
  ADD COLUMN IF NOT EXISTS sugar_g          NUMERIC(6,1),
  ADD COLUMN IF NOT EXISTS salt_g           NUMERIC(6,2),
  ADD COLUMN IF NOT EXISTS saturated_fat_g  NUMERIC(6,1),
  ADD COLUMN IF NOT EXISTS sodium_mg        INTEGER,
  ADD COLUMN IF NOT EXISTS serving_size     TEXT,
  ADD COLUMN IF NOT EXISTS serving_weight_g INTEGER,
  ADD COLUMN IF NOT EXISTS swap_options     TEXT[] NOT NULL DEFAULT '{{}}';

COMMIT;
"""

# ------------------------------------------------------------------ seed
COLS = ["external_id", "name", "category", "meal_type", "description", "calories",
        "protein_g", "carbs_g", "fat_g", "fibre_g", "sugar_g", "salt_g",
        "saturated_fat_g", "sodium_mg", "servings", "serving_size", "serving_weight_g",
        "prep_time_minutes", "cook_time_minutes", "source"]

rows = []
for r in recipes:
    vals = [q(r.get(c)) for c in COLS]
    vals.append(arr(r["goals"]))
    vals.append(arr(r["allergens"]))
    vals.append(arr(r["dietary_tags"]))
    vals.append(arr(r["swap_options"]))
    rows.append("  (" + ", ".join(vals) + ")")

NL = ",\n"
ing_rows = [f"  ({q(i['external_id'])}, {q(i['item'])}, {i['sort_order']})" for i in ingredients]
step_rows = [f"  ({q(s['external_id'])}, {s['step_number']}, {q(s['instruction'])})" for s in steps]

seed = f"""-- Auto-generated by scripts/prepare_owner_recipe_pack.py — DO NOT HAND-EDIT.
-- Seeds the owner's 2026-08 recipe pack: {len(recipes)} recipes, {len(ingredients)} ingredients, {len(steps)} steps.
--
-- Idempotent on external_id only, so the 927 pre-existing owner rows (external_id IS NULL)
-- are never touched. Re-running replaces just this pack.
--
-- Allergen data was remediated one-directionally before generation: allergens detected in
-- the ingredient text were ADDED, contradicted free-from tags were REMOVED, and nothing
-- ambiguous was auto-resolved. See docs/owner-recipe-pack-2026-08.md for the review queue.

BEGIN;

DELETE FROM public.recipes
 WHERE external_id ~ '^(BRK|LUN|DIN|SNK|CHT|DES)-[0-9]+$';   -- cascades to ingredients + steps

INSERT INTO public.recipes (
  {", ".join(COLS)}, goals, allergens, dietary_tags, swap_options
) VALUES
{NL.join(rows)};

INSERT INTO public.ingredients (recipe_id, item, sort_order)
SELECT r.id, v.item, v.sort_order
  FROM (VALUES
{NL.join(ing_rows)}
  ) AS v(external_id, item, sort_order)
  JOIN public.recipes r ON r.external_id = v.external_id;

INSERT INTO public.steps (recipe_id, step_number, instruction)
SELECT r.id, v.step_number, v.instruction
  FROM (VALUES
{NL.join(step_rows)}
  ) AS v(external_id, step_number, instruction)
  JOIN public.recipes r ON r.external_id = v.external_id;

COMMIT;
"""

a = f"{MIG}/20260810120000_recipes_meal_type_categories.sql"
b = f"{MIG}/20260810120100_seed_owner_recipe_pack_2026_08.sql"
open(a, "w").write(schema)
open(b, "w").write(seed)
print(f"wrote {a}  ({len(schema):,} bytes)")
print(f"wrote {b}  ({len(seed):,} bytes)")
