-- Auto-generated by scripts/gen_lean_protein_plant_pack.ts
-- 28-recipe lean high-protein plant pack (mains >=40g protein, <=10g fat).
-- Fixes protein undershoot + fat overshoot for vegetarian/vegan/dairy-free
-- users on high-protein and low-fat targets. Tagged 'hitt_leanpro_v1'.
-- Idempotent: re-running replaces only these rows.

BEGIN;

DELETE FROM public.recipes WHERE source = 'owner' AND category = 'lean'
  AND dietary_tags @> ARRAY['hitt_leanpro_v1']::TEXT[];

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Double Soya Protein Oats',
    'lean',
    'breakfast',
    512,
    45,
    65,
    8,
    ARRAY['vegan', 'hitt_leanpro_v1'],
    ARRAY['gluten', 'soya'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '60g rolled oats', 0),
    ((SELECT id FROM new_recipe), '2 scoops (60g) soya protein', 1),
    ((SELECT id FROM new_recipe), '300ml soya milk', 2),
    ((SELECT id FROM new_recipe), '1 banana', 3),
    ((SELECT id FROM new_recipe), '10g chia seeds', 4)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Combine the oats with the liquid in a pan or bowl.'),
    ((SELECT id FROM new_recipe), 2, 'Cook or microwave 2-3 minutes until creamy (or chill overnight).'),
    ((SELECT id FROM new_recipe), 3, 'Stir the protein through until smooth.'),
    ((SELECT id FROM new_recipe), 4, 'Top with the fruit and seeds. Serve.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Egg-White & Soya Mince Scramble on Toast',
    'lean',
    'breakfast',
    424,
    48,
    40,
    8,
    ARRAY['vegetarian', 'hitt_leanpro_v1'],
    ARRAY['eggs', 'gluten', 'soya'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '250g egg whites', 0),
    ((SELECT id FROM new_recipe), '40g rehydrated soya mince', 1),
    ((SELECT id FROM new_recipe), '2 slices wholemeal toast', 2),
    ((SELECT id FROM new_recipe), 'spinach & tomato', 3),
    ((SELECT id FROM new_recipe), 'paprika', 4)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Season the protein and sear in a hot non-stick pan with a light spray of oil until cooked through.'),
    ((SELECT id FROM new_recipe), 2, 'Cook the grain base per packet until fluffy.'),
    ((SELECT id FROM new_recipe), 3, 'Steam or sauté the vegetables for 3-4 minutes until just tender.'),
    ((SELECT id FROM new_recipe), 4, 'Plate the grain, top with the protein and vegetables.'),
    ((SELECT id FROM new_recipe), 5, 'Finish with the sauce and a crack of black pepper. Serve.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Pea-Protein Berry Smoothie XL',
    'lean',
    'breakfast',
    463,
    42,
    58,
    7,
    ARRAY['vegan', 'hitt_leanpro_v1'],
    ARRAY['gluten'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '2 scoops (60g) pea protein', 0),
    ((SELECT id FROM new_recipe), '150g frozen berries', 1),
    ((SELECT id FROM new_recipe), '1 banana', 2),
    ((SELECT id FROM new_recipe), '30g oats', 3),
    ((SELECT id FROM new_recipe), '350ml water', 4)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Add all ingredients to a blender with a handful of ice.'),
    ((SELECT id FROM new_recipe), 2, 'Blend on high until completely smooth.'),
    ((SELECT id FROM new_recipe), 3, 'Pour and serve; add toppings if serving as a bowl.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Soya Yogurt, Protein & Granola Bowl',
    'lean',
    'breakfast',
    481,
    40,
    60,
    9,
    ARRAY['vegan', 'hitt_leanpro_v1'],
    ARRAY['soya', 'gluten'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '300g high-protein soya yogurt', 0),
    ((SELECT id FROM new_recipe), '1 scoop (25g) soya protein', 1),
    ((SELECT id FROM new_recipe), '40g low-fat granola', 2),
    ((SELECT id FROM new_recipe), '80g berries', 3)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Prepare and portion each component.'),
    ((SELECT id FROM new_recipe), 2, 'Assemble on a plate or in a pot.'),
    ((SELECT id FROM new_recipe), 3, 'Shake or mix any liquid element and serve alongside.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'High-Protein Chickpea (Besan) Pancakes',
    'lean',
    'breakfast',
    441,
    40,
    50,
    9,
    ARRAY['vegan', 'gluten-free', 'hitt_leanpro_v1'],
    ARRAY[]::TEXT[],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '100g gram (chickpea) flour', 0),
    ((SELECT id FROM new_recipe), '1.5 scoops (40g) pea protein', 1),
    ((SELECT id FROM new_recipe), 'spinach & pepper', 2),
    ((SELECT id FROM new_recipe), 'light syrup', 3),
    ((SELECT id FROM new_recipe), 'water to batter', 4)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Combine the oats with the liquid in a pan or bowl.'),
    ((SELECT id FROM new_recipe), 2, 'Cook or microwave 2-3 minutes until creamy (or chill overnight).'),
    ((SELECT id FROM new_recipe), 3, 'Stir the protein through until smooth.'),
    ((SELECT id FROM new_recipe), 4, 'Top with the fruit and seeds. Serve.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Egg-White Omelette & Baked Beans',
    'lean',
    'breakfast',
    415,
    42,
    46,
    7,
    ARRAY['vegetarian', 'gluten-free', 'hitt_leanpro_v1'],
    ARRAY['eggs'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '250g egg whites', 0),
    ((SELECT id FROM new_recipe), '200g baked beans', 1),
    ((SELECT id FROM new_recipe), 'mushrooms & tomato', 2),
    ((SELECT id FROM new_recipe), 'chives', 3),
    ((SELECT id FROM new_recipe), 'black pepper', 4)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Season the protein and sear in a hot non-stick pan with a light spray of oil until cooked through.'),
    ((SELECT id FROM new_recipe), 2, 'Cook the grain base per packet until fluffy.'),
    ((SELECT id FROM new_recipe), 3, 'Steam or sauté the vegetables for 3-4 minutes until just tender.'),
    ((SELECT id FROM new_recipe), 4, 'Plate the grain, top with the protein and vegetables.'),
    ((SELECT id FROM new_recipe), 5, 'Finish with the sauce and a crack of black pepper. Serve.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Seitan Gyro Rice Bowl',
    'lean',
    'lunch',
    561,
    50,
    70,
    9,
    ARRAY['vegan', 'hitt_leanpro_v1'],
    ARRAY['gluten'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '170g seitan', 0),
    ((SELECT id FROM new_recipe), '200g cooked rice', 1),
    ((SELECT id FROM new_recipe), 'shredded salad & red onion', 2),
    ((SELECT id FROM new_recipe), 'garlic-herb sauce (dairy-free)', 3)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Season the protein and sear in a hot non-stick pan with a light spray of oil until cooked through.'),
    ((SELECT id FROM new_recipe), 2, 'Cook the grain base per packet until fluffy.'),
    ((SELECT id FROM new_recipe), 3, 'Steam or sauté the vegetables for 3-4 minutes until just tender.'),
    ((SELECT id FROM new_recipe), 4, 'Plate the grain, top with the protein and vegetables.'),
    ((SELECT id FROM new_recipe), 5, 'Finish with the sauce and a crack of black pepper. Serve.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Soya Mince Chilli & Rice',
    'lean',
    'lunch',
    552,
    48,
    72,
    8,
    ARRAY['vegan', 'gluten-free', 'hitt_leanpro_v1'],
    ARRAY['soya'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '70g dry soya mince', 0),
    ((SELECT id FROM new_recipe), '150g kidney beans', 1),
    ((SELECT id FROM new_recipe), '200g cooked rice', 2),
    ((SELECT id FROM new_recipe), 'tomato, onion, chilli', 3),
    ((SELECT id FROM new_recipe), 'cumin & paprika', 4)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Fry the aromatics in a light spray of oil for 1-2 minutes.'),
    ((SELECT id FROM new_recipe), 2, 'Add the protein and colour on all sides.'),
    ((SELECT id FROM new_recipe), 3, 'Stir in the spices and tomato base; simmer 10-12 minutes.'),
    ((SELECT id FROM new_recipe), 4, 'Serve over the cooked rice.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'High-Protein Lentil & Quinoa Bowl',
    'lean',
    'lunch',
    553,
    40,
    78,
    9,
    ARRAY['vegan', 'gluten-free', 'hitt_leanpro_v1'],
    ARRAY[]::TEXT[],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '150g cooked red lentils', 0),
    ((SELECT id FROM new_recipe), '150g cooked quinoa', 1),
    ((SELECT id FROM new_recipe), 'roasted veg', 2),
    ((SELECT id FROM new_recipe), 'lemon-herb dressing', 3),
    ((SELECT id FROM new_recipe), 'parsley', 4)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Prepare and portion each component.'),
    ((SELECT id FROM new_recipe), 2, 'Assemble on a plate or in a pot.'),
    ((SELECT id FROM new_recipe), 3, 'Shake or mix any liquid element and serve alongside.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Tempeh & Edamame Rice Bowl',
    'lean',
    'lunch',
    554,
    44,
    72,
    10,
    ARRAY['vegan', 'hitt_leanpro_v1'],
    ARRAY['soya', 'gluten', 'sesame'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '120g tempeh', 0),
    ((SELECT id FROM new_recipe), '80g edamame', 1),
    ((SELECT id FROM new_recipe), '200g cooked rice', 2),
    ((SELECT id FROM new_recipe), 'tamari & ginger', 3),
    ((SELECT id FROM new_recipe), 'sesame seeds', 4)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Sear the protein in a very hot wok with a light spray of oil.'),
    ((SELECT id FROM new_recipe), 2, 'Add the vegetables and stir-fry 3-4 minutes until crisp-tender.'),
    ((SELECT id FROM new_recipe), 3, 'Add the sauce and toss 1 minute to coat.'),
    ((SELECT id FROM new_recipe), 4, 'Serve over the rice or noodles.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Quorn & Sweet Potato Traybake',
    'lean',
    'lunch',
    524,
    45,
    68,
    8,
    ARRAY['vegetarian', 'gluten-free', 'hitt_leanpro_v1'],
    ARRAY['eggs'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '175g Quorn pieces', 0),
    ((SELECT id FROM new_recipe), '250g sweet potato', 1),
    ((SELECT id FROM new_recipe), 'peppers & courgette', 2),
    ((SELECT id FROM new_recipe), 'smoked paprika', 3)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Heat the oven to 200°C. Spread the protein and vegetables on a lined tray.'),
    ((SELECT id FROM new_recipe), 2, 'Season, spray lightly with oil, add the potato or grain.'),
    ((SELECT id FROM new_recipe), 3, 'Roast 20-25 minutes until cooked through.'),
    ((SELECT id FROM new_recipe), 4, 'Plate and finish with fresh herbs. Serve.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'TVP Bolognese Pasta',
    'lean',
    'lunch',
    576,
    46,
    80,
    8,
    ARRAY['vegan', 'hitt_leanpro_v1'],
    ARRAY['soya', 'gluten'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '70g dry soya mince (TVP)', 0),
    ((SELECT id FROM new_recipe), '90g dry pasta', 1),
    ((SELECT id FROM new_recipe), '250g passata', 2),
    ((SELECT id FROM new_recipe), 'carrot, onion, garlic', 3),
    ((SELECT id FROM new_recipe), 'basil', 4)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Cook the pasta in salted water until al dente, then drain.'),
    ((SELECT id FROM new_recipe), 2, 'Brown the protein in a non-stick pan with a light spray of oil.'),
    ((SELECT id FROM new_recipe), 3, 'Add the tomato base and simmer 5 minutes; season well.'),
    ((SELECT id FROM new_recipe), 4, 'Toss the pasta through and serve.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Falafel-Spiced Chickpea & Couscous',
    'lean',
    'lunch',
    554,
    40,
    76,
    10,
    ARRAY['vegan', 'hitt_leanpro_v1'],
    ARRAY['gluten', 'sesame', 'soya'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '200g chickpeas', 0),
    ((SELECT id FROM new_recipe), '80g dry couscous', 1),
    ((SELECT id FROM new_recipe), '80g edamame', 2),
    ((SELECT id FROM new_recipe), 'cucumber & tomato', 3),
    ((SELECT id FROM new_recipe), 'lemon-tahini drizzle', 4),
    ((SELECT id FROM new_recipe), 'coriander', 5)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Prepare and portion each component.'),
    ((SELECT id FROM new_recipe), 2, 'Assemble on a plate or in a pot.'),
    ((SELECT id FROM new_recipe), 3, 'Shake or mix any liquid element and serve alongside.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Edamame, Tofu & Soba Salad',
    'lean',
    'lunch',
    546,
    42,
    72,
    10,
    ARRAY['vegan', 'hitt_leanpro_v1'],
    ARRAY['soya', 'gluten', 'sesame'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '120g firm tofu', 0),
    ((SELECT id FROM new_recipe), '100g edamame', 1),
    ((SELECT id FROM new_recipe), '90g soba noodles', 2),
    ((SELECT id FROM new_recipe), 'sesame-ginger dressing', 3),
    ((SELECT id FROM new_recipe), 'spring onion', 4)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Prepare and portion each component.'),
    ((SELECT id FROM new_recipe), 2, 'Assemble on a plate or in a pot.'),
    ((SELECT id FROM new_recipe), 3, 'Shake or mix any liquid element and serve alongside.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Seitan Steak, Mash & Greens',
    'lean',
    'dinner',
    529,
    50,
    62,
    9,
    ARRAY['vegan', 'hitt_leanpro_v1'],
    ARRAY['gluten'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '180g seitan steak', 0),
    ((SELECT id FROM new_recipe), '300g potato mash (dairy-free)', 1),
    ((SELECT id FROM new_recipe), 'kale & green beans', 2),
    ((SELECT id FROM new_recipe), 'mustard-herb glaze', 3)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Heat the oven to 200°C. Spread the protein and vegetables on a lined tray.'),
    ((SELECT id FROM new_recipe), 2, 'Season, spray lightly with oil, add the potato or grain.'),
    ((SELECT id FROM new_recipe), 3, 'Roast 20-25 minutes until cooked through.'),
    ((SELECT id FROM new_recipe), 4, 'Plate and finish with fresh herbs. Serve.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Soya Mince Shepherd''s Pie',
    'lean',
    'dinner',
    545,
    46,
    70,
    9,
    ARRAY['vegan', 'gluten-free', 'hitt_leanpro_v1'],
    ARRAY['soya'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '70g dry soya mince', 0),
    ((SELECT id FROM new_recipe), '300g potato mash (dairy-free)', 1),
    ((SELECT id FROM new_recipe), 'carrot, peas, onion', 2),
    ((SELECT id FROM new_recipe), 'veg gravy', 3)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Heat the oven to 200°C. Spread the protein and vegetables on a lined tray.'),
    ((SELECT id FROM new_recipe), 2, 'Season, spray lightly with oil, add the potato or grain.'),
    ((SELECT id FROM new_recipe), 3, 'Roast 20-25 minutes until cooked through.'),
    ((SELECT id FROM new_recipe), 4, 'Plate and finish with fresh herbs. Serve.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'High-Protein Tofu & Chickpea Tikka with Rice',
    'lean',
    'dinner',
    578,
    44,
    78,
    10,
    ARRAY['vegan', 'gluten-free', 'hitt_leanpro_v1'],
    ARRAY['soya'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '150g firm tofu', 0),
    ((SELECT id FROM new_recipe), '120g chickpeas', 1),
    ((SELECT id FROM new_recipe), '200g cooked rice', 2),
    ((SELECT id FROM new_recipe), 'dairy-free tikka sauce', 3),
    ((SELECT id FROM new_recipe), 'coriander', 4)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Fry the aromatics in a light spray of oil for 1-2 minutes.'),
    ((SELECT id FROM new_recipe), 2, 'Add the protein and colour on all sides.'),
    ((SELECT id FROM new_recipe), 3, 'Stir in the spices and tomato base; simmer 10-12 minutes.'),
    ((SELECT id FROM new_recipe), 4, 'Serve over the cooked rice.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'TVP & Black Bean Burrito Bowl',
    'lean',
    'dinner',
    593,
    48,
    80,
    9,
    ARRAY['vegan', 'gluten-free', 'hitt_leanpro_v1'],
    ARRAY['soya'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '70g dry soya mince', 0),
    ((SELECT id FROM new_recipe), '150g black beans', 1),
    ((SELECT id FROM new_recipe), '180g cooked rice', 2),
    ((SELECT id FROM new_recipe), 'salsa & lime', 3),
    ((SELECT id FROM new_recipe), 'lettuce', 4)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Season the protein and sear in a hot non-stick pan with a light spray of oil until cooked through.'),
    ((SELECT id FROM new_recipe), 2, 'Cook the grain base per packet until fluffy.'),
    ((SELECT id FROM new_recipe), 3, 'Steam or sauté the vegetables for 3-4 minutes until just tender.'),
    ((SELECT id FROM new_recipe), 4, 'Plate the grain, top with the protein and vegetables.'),
    ((SELECT id FROM new_recipe), 5, 'Finish with the sauce and a crack of black pepper. Serve.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Seitan Stir-Fry with Noodles',
    'lean',
    'dinner',
    577,
    50,
    74,
    9,
    ARRAY['vegan', 'hitt_leanpro_v1'],
    ARRAY['gluten', 'soya', 'sesame'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '180g seitan', 0),
    ((SELECT id FROM new_recipe), '90g noodles', 1),
    ((SELECT id FROM new_recipe), 'broccoli, pepper, carrot', 2),
    ((SELECT id FROM new_recipe), 'tamari-garlic sauce', 3),
    ((SELECT id FROM new_recipe), 'sesame', 4)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Sear the protein in a very hot wok with a light spray of oil.'),
    ((SELECT id FROM new_recipe), 2, 'Add the vegetables and stir-fry 3-4 minutes until crisp-tender.'),
    ((SELECT id FROM new_recipe), 3, 'Add the sauce and toss 1 minute to coat.'),
    ((SELECT id FROM new_recipe), 4, 'Serve over the rice or noodles.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'High-Protein Red Lentil Dahl & Rice',
    'lean',
    'dinner',
    589,
    42,
    85,
    9,
    ARRAY['vegan', 'gluten-free', 'hitt_leanpro_v1'],
    ARRAY[]::TEXT[],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '140g dry red lentils', 0),
    ((SELECT id FROM new_recipe), '200g cooked rice', 1),
    ((SELECT id FROM new_recipe), 'tomato, onion, ginger', 2),
    ((SELECT id FROM new_recipe), 'cumin & turmeric', 3),
    ((SELECT id FROM new_recipe), 'spinach', 4)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Fry the aromatics in a light spray of oil for 1-2 minutes.'),
    ((SELECT id FROM new_recipe), 2, 'Add the protein and colour on all sides.'),
    ((SELECT id FROM new_recipe), 3, 'Stir in the spices and tomato base; simmer 10-12 minutes.'),
    ((SELECT id FROM new_recipe), 4, 'Serve over the cooked rice.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Quorn Fillet, Rice & Ratatouille',
    'lean',
    'dinner',
    536,
    46,
    70,
    8,
    ARRAY['vegetarian', 'gluten-free', 'hitt_leanpro_v1'],
    ARRAY['eggs'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '2 Quorn fillets', 0),
    ((SELECT id FROM new_recipe), '180g cooked rice', 1),
    ((SELECT id FROM new_recipe), 'aubergine, courgette, pepper, tomato', 2),
    ((SELECT id FROM new_recipe), 'herbs de Provence', 3)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Season the protein and sear in a hot non-stick pan with a light spray of oil until cooked through.'),
    ((SELECT id FROM new_recipe), 2, 'Cook the grain base per packet until fluffy.'),
    ((SELECT id FROM new_recipe), 3, 'Steam or sauté the vegetables for 3-4 minutes until just tender.'),
    ((SELECT id FROM new_recipe), 4, 'Plate the grain, top with the protein and vegetables.'),
    ((SELECT id FROM new_recipe), 5, 'Finish with the sauce and a crack of black pepper. Serve.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Tempeh Satay-Style with Rice',
    'lean',
    'dinner',
    562,
    42,
    76,
    10,
    ARRAY['vegan', 'gluten-free', 'hitt_leanpro_v1'],
    ARRAY['soya', 'peanuts'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '130g tempeh', 0),
    ((SELECT id FROM new_recipe), '200g cooked rice', 1),
    ((SELECT id FROM new_recipe), 'pak choi & pepper', 2),
    ((SELECT id FROM new_recipe), 'light peanut-soy sauce', 3),
    ((SELECT id FROM new_recipe), 'lime', 4)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Sear the protein in a very hot wok with a light spray of oil.'),
    ((SELECT id FROM new_recipe), 2, 'Add the vegetables and stir-fry 3-4 minutes until crisp-tender.'),
    ((SELECT id FROM new_recipe), 3, 'Add the sauce and toss 1 minute to coat.'),
    ((SELECT id FROM new_recipe), 4, 'Serve over the rice or noodles.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Soya Yogurt & Berry Protein Pot',
    'lean',
    'snack',
    354,
    30,
    45,
    6,
    ARRAY['vegan', 'gluten-free', 'hitt_leanpro_v1'],
    ARRAY['soya'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '300g high-protein soya yogurt', 0),
    ((SELECT id FROM new_recipe), '1/2 scoop (15g) soya protein', 1),
    ((SELECT id FROM new_recipe), '80g berries', 2),
    ((SELECT id FROM new_recipe), '10g seeds', 3)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Prepare and portion each component.'),
    ((SELECT id FROM new_recipe), 2, 'Assemble on a plate or in a pot.'),
    ((SELECT id FROM new_recipe), 3, 'Shake or mix any liquid element and serve alongside.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Roasted Edamame & Protein Shake',
    'lean',
    'snack',
    381,
    35,
    40,
    9,
    ARRAY['vegan', 'gluten-free', 'hitt_leanpro_v1'],
    ARRAY['soya'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '120g roasted edamame', 0),
    ((SELECT id FROM new_recipe), '1 scoop (30g) soya protein', 1),
    ((SELECT id FROM new_recipe), '300ml water', 2)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Prepare and portion each component.'),
    ((SELECT id FROM new_recipe), 2, 'Assemble on a plate or in a pot.'),
    ((SELECT id FROM new_recipe), 3, 'Shake or mix any liquid element and serve alongside.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Seitan Jerky & Rice Cakes',
    'lean',
    'snack',
    373,
    32,
    50,
    5,
    ARRAY['vegan', 'hitt_leanpro_v1'],
    ARRAY['gluten', 'soya'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '60g seitan jerky', 0),
    ((SELECT id FROM new_recipe), '3 rice cakes', 1),
    ((SELECT id FROM new_recipe), 'tamari glaze', 2)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Prepare and portion each component.'),
    ((SELECT id FROM new_recipe), 2, 'Assemble on a plate or in a pot.'),
    ((SELECT id FROM new_recipe), 3, 'Shake or mix any liquid element and serve alongside.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Pea-Protein & Banana Smoothie',
    'lean',
    'snack',
    401,
    34,
    55,
    5,
    ARRAY['vegan', 'gluten-free', 'hitt_leanpro_v1'],
    ARRAY[]::TEXT[],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '1 scoop (30g) pea protein', 0),
    ((SELECT id FROM new_recipe), '1 banana', 1),
    ((SELECT id FROM new_recipe), '30g oats', 2),
    ((SELECT id FROM new_recipe), '300ml water', 3)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Add all ingredients to a blender with a handful of ice.'),
    ((SELECT id FROM new_recipe), 2, 'Blend on high until completely smooth.'),
    ((SELECT id FROM new_recipe), 3, 'Pour and serve; add toppings if serving as a bowl.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'High-Protein Hummus & Pitta',
    'lean',
    'snack',
    422,
    28,
    55,
    10,
    ARRAY['vegan', 'hitt_leanpro_v1'],
    ARRAY['gluten', 'sesame'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '80g high-protein hummus', 0),
    ((SELECT id FROM new_recipe), '1 wholemeal pitta', 1),
    ((SELECT id FROM new_recipe), 'carrot & pepper sticks', 2)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Prepare and portion each component.'),
    ((SELECT id FROM new_recipe), 2, 'Assemble on a plate or in a pot.'),
    ((SELECT id FROM new_recipe), 3, 'Shake or mix any liquid element and serve alongside.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Roasted Chickpea & Soya Protein Plate',
    'lean',
    'snack',
    409,
    30,
    52,
    9,
    ARRAY['vegan', 'gluten-free', 'hitt_leanpro_v1'],
    ARRAY['soya'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '150g roasted chickpeas', 0),
    ((SELECT id FROM new_recipe), '1/2 scoop (15g) soya protein shake', 1),
    ((SELECT id FROM new_recipe), 'cherry tomatoes', 2)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Prepare and portion each component.'),
    ((SELECT id FROM new_recipe), 2, 'Assemble on a plate or in a pot.'),
    ((SELECT id FROM new_recipe), 3, 'Shake or mix any liquid element and serve alongside.');

COMMIT;