-- Auto-generated by scripts/gen_lean_dense_pack.ts
-- 44-recipe lean + calorie-dense pack (≥400 kcal / ≤10g fat).
-- Fills the low-fat calorie-dense gap so low-fat and high-carb athletic
-- macro targets can be matched. Tagged 'hitt_lean_v1' for later replacement.
-- Idempotent: re-running replaces only these rows.

BEGIN;

DELETE FROM public.recipes WHERE source = 'owner' AND category = 'lean'
  AND dietary_tags @> ARRAY['hitt_lean_v1']::TEXT[];

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Protein Oats with Banana & Berries',
    'lean',
    'breakfast',
    524,
    35,
    78,
    8,
    ARRAY['vegan', 'hitt_lean_v1'],
    ARRAY['gluten', 'soya'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '60g rolled oats', 0),
    ((SELECT id FROM new_recipe), '300ml soya milk', 1),
    ((SELECT id FROM new_recipe), '1 scoop (30g) soya protein', 2),
    ((SELECT id FROM new_recipe), '1 banana, sliced', 3),
    ((SELECT id FROM new_recipe), '80g mixed berries', 4),
    ((SELECT id FROM new_recipe), '10g chia seeds', 5)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Combine the oats with the liquid in a pan or bowl.'),
    ((SELECT id FROM new_recipe), 2, 'Cook on the hob or microwave for 2-3 minutes until creamy (or chill overnight).'),
    ((SELECT id FROM new_recipe), 3, 'Stir the protein through until smooth.'),
    ((SELECT id FROM new_recipe), 4, 'Top with the fruit and any seeds. Serve warm or cold.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Egg-White & Turkey Breakfast Wrap',
    'lean',
    'breakfast',
    457,
    42,
    52,
    9,
    ARRAY['hitt_lean_v1'],
    ARRAY['gluten', 'eggs'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '1 large wholemeal wrap', 0),
    ((SELECT id FROM new_recipe), '200g egg whites', 1),
    ((SELECT id FROM new_recipe), '80g lean turkey rasher', 2),
    ((SELECT id FROM new_recipe), 'handful spinach', 3),
    ((SELECT id FROM new_recipe), '2 tbsp salsa', 4)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Cook and season the filling in a non-stick pan until done.'),
    ((SELECT id FROM new_recipe), 2, 'Warm the wrap or base briefly.'),
    ((SELECT id FROM new_recipe), 3, 'Fill, add the salad and sauce, and fold. Serve.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Chicken & Rice Breakfast Bowl',
    'lean',
    'breakfast',
    540,
    45,
    72,
    8,
    ARRAY['gluten-free', 'hitt_lean_v1'],
    ARRAY[]::TEXT[],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '120g chicken breast', 0),
    ((SELECT id FROM new_recipe), '180g cooked white rice', 1),
    ((SELECT id FROM new_recipe), '1 egg white', 2),
    ((SELECT id FROM new_recipe), '60g peas', 3),
    ((SELECT id FROM new_recipe), 'soy-free seasoning', 4)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Season the protein and cook in a hot non-stick pan (or grill) with a light spray of oil until cooked through.'),
    ((SELECT id FROM new_recipe), 2, 'Cook the grain base per packet, keeping it fluffy.'),
    ((SELECT id FROM new_recipe), 3, 'Steam or sauté the vegetables for 3-4 minutes until just tender.'),
    ((SELECT id FROM new_recipe), 4, 'Plate the grain as a base, top with the protein and vegetables.'),
    ((SELECT id FROM new_recipe), 5, 'Finish with the sauce or seasoning and a crack of black pepper. Serve.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Smoked Haddock & Poached Egg-White on Toast',
    'lean',
    'breakfast',
    433,
    40,
    48,
    9,
    ARRAY['hitt_lean_v1'],
    ARRAY['gluten', 'fish', 'eggs'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '120g smoked haddock', 0),
    ((SELECT id FROM new_recipe), '2 slices wholemeal bread', 1),
    ((SELECT id FROM new_recipe), '2 egg whites, poached', 2),
    ((SELECT id FROM new_recipe), '80g spinach', 3),
    ((SELECT id FROM new_recipe), 'lemon & pepper', 4)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Heat the oven to 200°C. Spread the protein and vegetables on a lined tray.'),
    ((SELECT id FROM new_recipe), 2, 'Season, spray lightly with oil, and add the potato or grain.'),
    ((SELECT id FROM new_recipe), 3, 'Roast 20-25 minutes until cooked through and golden.'),
    ((SELECT id FROM new_recipe), 4, 'Plate up and finish with fresh herbs. Serve.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Berry Protein Smoothie Bowl',
    'lean',
    'breakfast',
    483,
    35,
    70,
    7,
    ARRAY['vegan', 'gluten-free', 'hitt_lean_v1'],
    ARRAY['soya'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '1.5 scoops (45g) soya protein', 0),
    ((SELECT id FROM new_recipe), '150g frozen berries', 1),
    ((SELECT id FROM new_recipe), '1 banana', 2),
    ((SELECT id FROM new_recipe), '250ml water', 3),
    ((SELECT id FROM new_recipe), '20g granola-free oats', 4),
    ((SELECT id FROM new_recipe), 'seeds to top', 5)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Add all ingredients to a blender with a handful of ice.'),
    ((SELECT id FROM new_recipe), 2, 'Blend on high until completely smooth.'),
    ((SELECT id FROM new_recipe), 3, 'Pour into a glass or bowl; add the toppings if serving as a bowl.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Tofu Scramble & Beans on Toast',
    'lean',
    'breakfast',
    450,
    32,
    58,
    10,
    ARRAY['vegan', 'hitt_lean_v1'],
    ARRAY['gluten', 'soya'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '150g firm tofu', 0),
    ((SELECT id FROM new_recipe), '200g baked beans', 1),
    ((SELECT id FROM new_recipe), '2 slices wholemeal bread', 2),
    ((SELECT id FROM new_recipe), 'turmeric & black salt', 3),
    ((SELECT id FROM new_recipe), 'handful spinach', 4)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Season the protein and cook in a hot non-stick pan (or grill) with a light spray of oil until cooked through.'),
    ((SELECT id FROM new_recipe), 2, 'Cook the grain base per packet, keeping it fluffy.'),
    ((SELECT id FROM new_recipe), 3, 'Steam or sauté the vegetables for 3-4 minutes until just tender.'),
    ((SELECT id FROM new_recipe), 4, 'Plate the grain as a base, top with the protein and vegetables.'),
    ((SELECT id FROM new_recipe), 5, 'Finish with the sauce or seasoning and a crack of black pepper. Serve.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Banana Protein Pancakes',
    'lean',
    'breakfast',
    497,
    38,
    66,
    9,
    ARRAY['vegetarian', 'hitt_lean_v1'],
    ARRAY['gluten', 'eggs'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '1 banana', 0),
    ((SELECT id FROM new_recipe), '3 egg whites', 1),
    ((SELECT id FROM new_recipe), '50g oat flour', 2),
    ((SELECT id FROM new_recipe), '1 scoop (25g) whey', 3),
    ((SELECT id FROM new_recipe), 'berries to top', 4),
    ((SELECT id FROM new_recipe), 'light maple syrup', 5)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Combine the oats with the liquid in a pan or bowl.'),
    ((SELECT id FROM new_recipe), 2, 'Cook on the hob or microwave for 2-3 minutes until creamy (or chill overnight).'),
    ((SELECT id FROM new_recipe), 3, 'Stir the protein through until smooth.'),
    ((SELECT id FROM new_recipe), 4, 'Top with the fruit and any seeds. Serve warm or cold.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Overnight Oats, Apple & Cinnamon',
    'lean',
    'breakfast',
    492,
    30,
    75,
    8,
    ARRAY['vegan', 'hitt_lean_v1'],
    ARRAY['gluten', 'soya'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '70g rolled oats', 0),
    ((SELECT id FROM new_recipe), '300ml soya milk', 1),
    ((SELECT id FROM new_recipe), '1 scoop (25g) soya protein', 2),
    ((SELECT id FROM new_recipe), '1 grated apple', 3),
    ((SELECT id FROM new_recipe), 'cinnamon', 4),
    ((SELECT id FROM new_recipe), '10g raisins', 5)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Combine the oats with the liquid in a pan or bowl.'),
    ((SELECT id FROM new_recipe), 2, 'Cook on the hob or microwave for 2-3 minutes until creamy (or chill overnight).'),
    ((SELECT id FROM new_recipe), 3, 'Stir the protein through until smooth.'),
    ((SELECT id FROM new_recipe), 4, 'Top with the fruit and any seeds. Serve warm or cold.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Prawn & Egg-White Rice Congee',
    'lean',
    'breakfast',
    462,
    40,
    62,
    6,
    ARRAY['gluten-free', 'hitt_lean_v1'],
    ARRAY['crustaceans', 'eggs'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '100g king prawns', 0),
    ((SELECT id FROM new_recipe), '180g cooked rice', 1),
    ((SELECT id FROM new_recipe), '2 egg whites', 2),
    ((SELECT id FROM new_recipe), 'spring onion & ginger', 3),
    ((SELECT id FROM new_recipe), 'low-salt stock', 4)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Season the protein and cook in a hot non-stick pan (or grill) with a light spray of oil until cooked through.'),
    ((SELECT id FROM new_recipe), 2, 'Cook the grain base per packet, keeping it fluffy.'),
    ((SELECT id FROM new_recipe), 3, 'Steam or sauté the vegetables for 3-4 minutes until just tender.'),
    ((SELECT id FROM new_recipe), 4, 'Plate the grain as a base, top with the protein and vegetables.'),
    ((SELECT id FROM new_recipe), 5, 'Finish with the sauce or seasoning and a crack of black pepper. Serve.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Turkey & Potato Breakfast Hash',
    'lean',
    'breakfast',
    458,
    42,
    50,
    10,
    ARRAY['gluten-free', 'hitt_lean_v1'],
    ARRAY['eggs'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '120g lean turkey mince', 0),
    ((SELECT id FROM new_recipe), '200g diced potato', 1),
    ((SELECT id FROM new_recipe), '2 egg whites', 2),
    ((SELECT id FROM new_recipe), 'peppers & onion', 3),
    ((SELECT id FROM new_recipe), 'paprika', 4)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Heat the oven to 200°C. Spread the protein and vegetables on a lined tray.'),
    ((SELECT id FROM new_recipe), 2, 'Season, spray lightly with oil, and add the potato or grain.'),
    ((SELECT id FROM new_recipe), 3, 'Roast 20-25 minutes until cooked through and golden.'),
    ((SELECT id FROM new_recipe), 4, 'Plate up and finish with fresh herbs. Serve.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Mango & Pea-Protein Smoothie + Bagel',
    'lean',
    'breakfast',
    519,
    34,
    80,
    7,
    ARRAY['vegan', 'hitt_lean_v1'],
    ARRAY['gluten'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '1.5 scoops (45g) pea protein', 0),
    ((SELECT id FROM new_recipe), '150g mango', 1),
    ((SELECT id FROM new_recipe), '1 plain bagel', 2),
    ((SELECT id FROM new_recipe), '250ml water', 3),
    ((SELECT id FROM new_recipe), '1 tsp honey-free syrup', 4)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Add all ingredients to a blender with a handful of ice.'),
    ((SELECT id FROM new_recipe), 2, 'Blend on high until completely smooth.'),
    ((SELECT id FROM new_recipe), 3, 'Pour into a glass or bowl; add the toppings if serving as a bowl.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Chicken, Rice & Roasted Veg Bowl',
    'lean',
    'lunch',
    585,
    48,
    78,
    9,
    ARRAY['gluten-free', 'hitt_lean_v1'],
    ARRAY[]::TEXT[],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '150g chicken breast', 0),
    ((SELECT id FROM new_recipe), '200g cooked rice', 1),
    ((SELECT id FROM new_recipe), '150g roasted courgette & pepper', 2),
    ((SELECT id FROM new_recipe), 'lemon & herbs', 3)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Season the protein and cook in a hot non-stick pan (or grill) with a light spray of oil until cooked through.'),
    ((SELECT id FROM new_recipe), 2, 'Cook the grain base per packet, keeping it fluffy.'),
    ((SELECT id FROM new_recipe), 3, 'Steam or sauté the vegetables for 3-4 minutes until just tender.'),
    ((SELECT id FROM new_recipe), 4, 'Plate the grain as a base, top with the protein and vegetables.'),
    ((SELECT id FROM new_recipe), 5, 'Finish with the sauce or seasoning and a crack of black pepper. Serve.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Tuna & Sweet Potato Poke',
    'lean',
    'lunch',
    532,
    45,
    70,
    8,
    ARRAY['gluten-free', 'hitt_lean_v1'],
    ARRAY['fish', 'soya', 'sesame'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '150g tuna steak', 0),
    ((SELECT id FROM new_recipe), '220g roasted sweet potato', 1),
    ((SELECT id FROM new_recipe), 'edamame', 2),
    ((SELECT id FROM new_recipe), 'tamari & sesame', 3),
    ((SELECT id FROM new_recipe), 'cucumber', 4)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Season the protein and cook in a hot non-stick pan (or grill) with a light spray of oil until cooked through.'),
    ((SELECT id FROM new_recipe), 2, 'Cook the grain base per packet, keeping it fluffy.'),
    ((SELECT id FROM new_recipe), 3, 'Steam or sauté the vegetables for 3-4 minutes until just tender.'),
    ((SELECT id FROM new_recipe), 4, 'Plate the grain as a base, top with the protein and vegetables.'),
    ((SELECT id FROM new_recipe), 5, 'Finish with the sauce or seasoning and a crack of black pepper. Serve.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Turkey Meatball Pasta',
    'lean',
    'lunch',
    602,
    46,
    82,
    10,
    ARRAY['hitt_lean_v1'],
    ARRAY['gluten'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '150g lean turkey mince', 0),
    ((SELECT id FROM new_recipe), '90g dry pasta', 1),
    ((SELECT id FROM new_recipe), '200g tomato passata', 2),
    ((SELECT id FROM new_recipe), 'garlic & basil', 3),
    ((SELECT id FROM new_recipe), 'spinach', 4)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Cook the pasta in salted water until al dente, then drain.'),
    ((SELECT id FROM new_recipe), 2, 'Brown the protein in a non-stick pan with a light spray of oil.'),
    ((SELECT id FROM new_recipe), 3, 'Add the tomato base and simmer 5 minutes; season well.'),
    ((SELECT id FROM new_recipe), 4, 'Toss the pasta through the sauce and serve.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Prawn Noodle Stir-Fry',
    'lean',
    'lunch',
    544,
    42,
    76,
    8,
    ARRAY['hitt_lean_v1'],
    ARRAY['crustaceans', 'gluten', 'soya'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '140g king prawns', 0),
    ((SELECT id FROM new_recipe), '90g rice noodles', 1),
    ((SELECT id FROM new_recipe), 'stir-fry vegetables', 2),
    ((SELECT id FROM new_recipe), 'tamari & ginger', 3),
    ((SELECT id FROM new_recipe), 'lime', 4)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Cook the protein in a very hot wok with a light spray of oil until seared.'),
    ((SELECT id FROM new_recipe), 2, 'Add the vegetables and stir-fry 3-4 minutes until crisp-tender.'),
    ((SELECT id FROM new_recipe), 3, 'Add the sauce and toss for 1 minute to coat.'),
    ((SELECT id FROM new_recipe), 4, 'Serve over the rice or noodles.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Lentil & Rice Dahl',
    'lean',
    'lunch',
    533,
    28,
    85,
    9,
    ARRAY['vegan', 'gluten-free', 'hitt_lean_v1'],
    ARRAY[]::TEXT[],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '120g red lentils', 0),
    ((SELECT id FROM new_recipe), '150g cooked basmati', 1),
    ((SELECT id FROM new_recipe), 'tomato & onion', 2),
    ((SELECT id FROM new_recipe), 'cumin, turmeric, ginger', 3),
    ((SELECT id FROM new_recipe), 'spinach', 4)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Fry the aromatics in a light spray of oil for 1-2 minutes.'),
    ((SELECT id FROM new_recipe), 2, 'Add the protein and colour on all sides.'),
    ((SELECT id FROM new_recipe), 3, 'Stir in the spices and tomato/coconut base; simmer 10-12 minutes.'),
    ((SELECT id FROM new_recipe), 4, 'Serve over the cooked rice.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Chickpea & Quinoa Power Salad',
    'lean',
    'lunch',
    514,
    26,
    80,
    10,
    ARRAY['vegan', 'gluten-free', 'hitt_lean_v1'],
    ARRAY[]::TEXT[],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '150g chickpeas', 0),
    ((SELECT id FROM new_recipe), '120g cooked quinoa', 1),
    ((SELECT id FROM new_recipe), 'cucumber, tomato, red onion', 2),
    ((SELECT id FROM new_recipe), 'lemon-tahini drizzle', 3),
    ((SELECT id FROM new_recipe), 'parsley', 4)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Prepare and portion each component.'),
    ((SELECT id FROM new_recipe), 2, 'Assemble on a plate or in a pot.'),
    ((SELECT id FROM new_recipe), 3, 'Mix or shake any liquid element and serve alongside.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Grilled Chicken & Couscous Tabbouleh',
    'lean',
    'lunch',
    557,
    47,
    72,
    9,
    ARRAY['hitt_lean_v1'],
    ARRAY['gluten'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '150g chicken breast', 0),
    ((SELECT id FROM new_recipe), '80g dry couscous', 1),
    ((SELECT id FROM new_recipe), 'tomato, cucumber, mint', 2),
    ((SELECT id FROM new_recipe), 'lemon', 3),
    ((SELECT id FROM new_recipe), 'parsley', 4)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Season the protein and cook in a hot non-stick pan (or grill) with a light spray of oil until cooked through.'),
    ((SELECT id FROM new_recipe), 2, 'Cook the grain base per packet, keeping it fluffy.'),
    ((SELECT id FROM new_recipe), 3, 'Steam or sauté the vegetables for 3-4 minutes until just tender.'),
    ((SELECT id FROM new_recipe), 4, 'Plate the grain as a base, top with the protein and vegetables.'),
    ((SELECT id FROM new_recipe), 5, 'Finish with the sauce or seasoning and a crack of black pepper. Serve.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'White Fish & Potato Traybake',
    'lean',
    'lunch',
    520,
    44,
    68,
    8,
    ARRAY['gluten-free', 'hitt_lean_v1'],
    ARRAY['fish'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '160g cod loin', 0),
    ((SELECT id FROM new_recipe), '250g new potatoes', 1),
    ((SELECT id FROM new_recipe), 'green beans', 2),
    ((SELECT id FROM new_recipe), 'lemon & dill', 3)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Heat the oven to 200°C. Spread the protein and vegetables on a lined tray.'),
    ((SELECT id FROM new_recipe), 2, 'Season, spray lightly with oil, and add the potato or grain.'),
    ((SELECT id FROM new_recipe), 3, 'Roast 20-25 minutes until cooked through and golden.'),
    ((SELECT id FROM new_recipe), 4, 'Plate up and finish with fresh herbs. Serve.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Teriyaki Tofu & Rice Bowl',
    'lean',
    'lunch',
    562,
    30,
    88,
    10,
    ARRAY['vegan', 'hitt_lean_v1'],
    ARRAY['soya', 'gluten', 'sesame'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '180g firm tofu', 0),
    ((SELECT id FROM new_recipe), '200g cooked rice', 1),
    ((SELECT id FROM new_recipe), 'teriyaki (tamari base)', 2),
    ((SELECT id FROM new_recipe), 'broccoli & carrot', 3),
    ((SELECT id FROM new_recipe), 'sesame seeds', 4)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Cook the protein in a very hot wok with a light spray of oil until seared.'),
    ((SELECT id FROM new_recipe), 2, 'Add the vegetables and stir-fry 3-4 minutes until crisp-tender.'),
    ((SELECT id FROM new_recipe), 3, 'Add the sauce and toss for 1 minute to coat.'),
    ((SELECT id FROM new_recipe), 4, 'Serve over the rice or noodles.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Turkey & Black Bean Burrito Bowl',
    'lean',
    'lunch',
    594,
    46,
    80,
    10,
    ARRAY['gluten-free', 'hitt_lean_v1'],
    ARRAY[]::TEXT[],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '150g lean turkey mince', 0),
    ((SELECT id FROM new_recipe), '150g cooked rice', 1),
    ((SELECT id FROM new_recipe), '150g black beans', 2),
    ((SELECT id FROM new_recipe), 'salsa & lime', 3),
    ((SELECT id FROM new_recipe), 'lettuce', 4)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Season the protein and cook in a hot non-stick pan (or grill) with a light spray of oil until cooked through.'),
    ((SELECT id FROM new_recipe), 2, 'Cook the grain base per packet, keeping it fluffy.'),
    ((SELECT id FROM new_recipe), 3, 'Steam or sauté the vegetables for 3-4 minutes until just tender.'),
    ((SELECT id FROM new_recipe), 4, 'Plate the grain as a base, top with the protein and vegetables.'),
    ((SELECT id FROM new_recipe), 5, 'Finish with the sauce or seasoning and a crack of black pepper. Serve.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Edamame & Brown Rice Buddha Bowl',
    'lean',
    'lunch',
    530,
    28,
    82,
    10,
    ARRAY['vegan', 'gluten-free', 'hitt_lean_v1'],
    ARRAY['soya', 'sesame'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '150g edamame', 0),
    ((SELECT id FROM new_recipe), '200g cooked brown rice', 1),
    ((SELECT id FROM new_recipe), 'shredded carrot & cabbage', 2),
    ((SELECT id FROM new_recipe), 'sesame-ginger dressing', 3),
    ((SELECT id FROM new_recipe), 'nori', 4)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Prepare and portion each component.'),
    ((SELECT id FROM new_recipe), 2, 'Assemble on a plate or in a pot.'),
    ((SELECT id FROM new_recipe), 3, 'Mix or shake any liquid element and serve alongside.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Grilled Chicken, Mash & Greens',
    'lean',
    'dinner',
    541,
    50,
    65,
    9,
    ARRAY['gluten-free', 'hitt_lean_v1'],
    ARRAY[]::TEXT[],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '160g chicken breast', 0),
    ((SELECT id FROM new_recipe), '300g potato mash (no butter)', 1),
    ((SELECT id FROM new_recipe), '150g green beans & kale', 2),
    ((SELECT id FROM new_recipe), 'gravy (lean)', 3)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Heat the oven to 200°C. Spread the protein and vegetables on a lined tray.'),
    ((SELECT id FROM new_recipe), 2, 'Season, spray lightly with oil, and add the potato or grain.'),
    ((SELECT id FROM new_recipe), 3, 'Roast 20-25 minutes until cooked through and golden.'),
    ((SELECT id FROM new_recipe), 4, 'Plate up and finish with fresh herbs. Serve.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Cod, New Potatoes & Peas',
    'lean',
    'dinner',
    504,
    46,
    62,
    8,
    ARRAY['gluten-free', 'hitt_lean_v1'],
    ARRAY['fish'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '180g cod loin', 0),
    ((SELECT id FROM new_recipe), '250g new potatoes', 1),
    ((SELECT id FROM new_recipe), '120g peas', 2),
    ((SELECT id FROM new_recipe), 'lemon & parsley', 3)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Heat the oven to 200°C. Spread the protein and vegetables on a lined tray.'),
    ((SELECT id FROM new_recipe), 2, 'Season, spray lightly with oil, and add the potato or grain.'),
    ((SELECT id FROM new_recipe), 3, 'Roast 20-25 minutes until cooked through and golden.'),
    ((SELECT id FROM new_recipe), 4, 'Plate up and finish with fresh herbs. Serve.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Turkey Bolognese with Spaghetti',
    'lean',
    'dinner',
    622,
    48,
    85,
    10,
    ARRAY['hitt_lean_v1'],
    ARRAY['gluten'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '160g lean turkey mince', 0),
    ((SELECT id FROM new_recipe), '95g dry spaghetti', 1),
    ((SELECT id FROM new_recipe), '250g passata', 2),
    ((SELECT id FROM new_recipe), 'carrot, onion, garlic', 3),
    ((SELECT id FROM new_recipe), 'basil', 4)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Cook the pasta in salted water until al dente, then drain.'),
    ((SELECT id FROM new_recipe), 2, 'Brown the protein in a non-stick pan with a light spray of oil.'),
    ((SELECT id FROM new_recipe), 3, 'Add the tomato base and simmer 5 minutes; season well.'),
    ((SELECT id FROM new_recipe), 4, 'Toss the pasta through the sauce and serve.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'King Prawn & Vegetable Paella',
    'lean',
    'dinner',
    577,
    44,
    80,
    9,
    ARRAY['gluten-free', 'hitt_lean_v1'],
    ARRAY['crustaceans'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '150g king prawns', 0),
    ((SELECT id FROM new_recipe), '90g paella rice', 1),
    ((SELECT id FROM new_recipe), 'peppers, peas, tomato', 2),
    ((SELECT id FROM new_recipe), 'smoked paprika & saffron', 3),
    ((SELECT id FROM new_recipe), 'lemon', 4)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Season the protein and cook in a hot non-stick pan (or grill) with a light spray of oil until cooked through.'),
    ((SELECT id FROM new_recipe), 2, 'Cook the grain base per packet, keeping it fluffy.'),
    ((SELECT id FROM new_recipe), 3, 'Steam or sauté the vegetables for 3-4 minutes until just tender.'),
    ((SELECT id FROM new_recipe), 4, 'Plate the grain as a base, top with the protein and vegetables.'),
    ((SELECT id FROM new_recipe), 5, 'Finish with the sauce or seasoning and a crack of black pepper. Serve.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Chicken Tikka & Basmati Rice',
    'lean',
    'dinner',
    602,
    50,
    78,
    10,
    ARRAY['gluten-free', 'hitt_lean_v1'],
    ARRAY[]::TEXT[],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '160g chicken breast', 0),
    ((SELECT id FROM new_recipe), '200g cooked basmati', 1),
    ((SELECT id FROM new_recipe), 'dairy-free tikka marinade', 2),
    ((SELECT id FROM new_recipe), 'onion & tomato', 3),
    ((SELECT id FROM new_recipe), 'coriander', 4)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Fry the aromatics in a light spray of oil for 1-2 minutes.'),
    ((SELECT id FROM new_recipe), 2, 'Add the protein and colour on all sides.'),
    ((SELECT id FROM new_recipe), 3, 'Stir in the spices and tomato/coconut base; simmer 10-12 minutes.'),
    ((SELECT id FROM new_recipe), 4, 'Serve over the cooked rice.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Tofu & Vegetable Pad Thai',
    'lean',
    'dinner',
    578,
    30,
    92,
    10,
    ARRAY['vegan', 'hitt_lean_v1'],
    ARRAY['soya', 'gluten'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '180g firm tofu', 0),
    ((SELECT id FROM new_recipe), '100g rice noodles', 1),
    ((SELECT id FROM new_recipe), 'beansprouts & carrot', 2),
    ((SELECT id FROM new_recipe), 'tamarind-tamari sauce', 3),
    ((SELECT id FROM new_recipe), 'lime & spring onion', 4)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Cook the protein in a very hot wok with a light spray of oil until seared.'),
    ((SELECT id FROM new_recipe), 2, 'Add the vegetables and stir-fry 3-4 minutes until crisp-tender.'),
    ((SELECT id FROM new_recipe), 3, 'Add the sauce and toss for 1 minute to coat.'),
    ((SELECT id FROM new_recipe), 4, 'Serve over the rice or noodles.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Lean Beef & Broccoli with Rice',
    'lean',
    'dinner',
    578,
    50,
    72,
    10,
    ARRAY['hitt_lean_v1'],
    ARRAY['soya', 'gluten'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '150g lean beef strips (5% fat)', 0),
    ((SELECT id FROM new_recipe), '200g cooked rice', 1),
    ((SELECT id FROM new_recipe), '200g broccoli', 2),
    ((SELECT id FROM new_recipe), 'tamari & garlic', 3),
    ((SELECT id FROM new_recipe), 'ginger', 4)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Cook the protein in a very hot wok with a light spray of oil until seared.'),
    ((SELECT id FROM new_recipe), 2, 'Add the vegetables and stir-fry 3-4 minutes until crisp-tender.'),
    ((SELECT id FROM new_recipe), 3, 'Add the sauce and toss for 1 minute to coat.'),
    ((SELECT id FROM new_recipe), 4, 'Serve over the rice or noodles.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Seitan Steak, Sweet Potato & Kale',
    'lean',
    'dinner',
    541,
    45,
    70,
    9,
    ARRAY['vegan', 'hitt_lean_v1'],
    ARRAY['gluten'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '150g seitan', 0),
    ((SELECT id FROM new_recipe), '250g sweet potato', 1),
    ((SELECT id FROM new_recipe), '120g kale', 2),
    ((SELECT id FROM new_recipe), 'mustard-herb glaze', 3)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Heat the oven to 200°C. Spread the protein and vegetables on a lined tray.'),
    ((SELECT id FROM new_recipe), 2, 'Season, spray lightly with oil, and add the potato or grain.'),
    ((SELECT id FROM new_recipe), 3, 'Roast 20-25 minutes until cooked through and golden.'),
    ((SELECT id FROM new_recipe), 4, 'Plate up and finish with fresh herbs. Serve.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Chicken & Chickpea Curry with Rice',
    'lean',
    'dinner',
    602,
    46,
    82,
    10,
    ARRAY['gluten-free', 'hitt_lean_v1'],
    ARRAY[]::TEXT[],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '140g chicken breast', 0),
    ((SELECT id FROM new_recipe), '120g chickpeas', 1),
    ((SELECT id FROM new_recipe), '200g cooked rice', 2),
    ((SELECT id FROM new_recipe), 'tomato & spice base', 3),
    ((SELECT id FROM new_recipe), 'spinach', 4)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Fry the aromatics in a light spray of oil for 1-2 minutes.'),
    ((SELECT id FROM new_recipe), 2, 'Add the protein and colour on all sides.'),
    ((SELECT id FROM new_recipe), 3, 'Stir in the spices and tomato/coconut base; simmer 10-12 minutes.'),
    ((SELECT id FROM new_recipe), 4, 'Serve over the cooked rice.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Grilled Prawn & Quinoa Primavera',
    'lean',
    'dinner',
    545,
    42,
    74,
    9,
    ARRAY['gluten-free', 'hitt_lean_v1'],
    ARRAY['crustaceans'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '150g king prawns', 0),
    ((SELECT id FROM new_recipe), '160g cooked quinoa', 1),
    ((SELECT id FROM new_recipe), 'courgette, peas, asparagus', 2),
    ((SELECT id FROM new_recipe), 'lemon & garlic', 3)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Season the protein and cook in a hot non-stick pan (or grill) with a light spray of oil until cooked through.'),
    ((SELECT id FROM new_recipe), 2, 'Cook the grain base per packet, keeping it fluffy.'),
    ((SELECT id FROM new_recipe), 3, 'Steam or sauté the vegetables for 3-4 minutes until just tender.'),
    ((SELECT id FROM new_recipe), 4, 'Plate the grain as a base, top with the protein and vegetables.'),
    ((SELECT id FROM new_recipe), 5, 'Finish with the sauce or seasoning and a crack of black pepper. Serve.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Turkey Steak, Rice & Ratatouille',
    'lean',
    'dinner',
    552,
    50,
    70,
    8,
    ARRAY['gluten-free', 'hitt_lean_v1'],
    ARRAY[]::TEXT[],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '170g turkey breast steak', 0),
    ((SELECT id FROM new_recipe), '180g cooked rice', 1),
    ((SELECT id FROM new_recipe), 'aubergine, courgette, pepper, tomato', 2),
    ((SELECT id FROM new_recipe), 'herbs de Provence', 3)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Season the protein and cook in a hot non-stick pan (or grill) with a light spray of oil until cooked through.'),
    ((SELECT id FROM new_recipe), 2, 'Cook the grain base per packet, keeping it fluffy.'),
    ((SELECT id FROM new_recipe), 3, 'Steam or sauté the vegetables for 3-4 minutes until just tender.'),
    ((SELECT id FROM new_recipe), 4, 'Plate the grain as a base, top with the protein and vegetables.'),
    ((SELECT id FROM new_recipe), 5, 'Finish with the sauce or seasoning and a crack of black pepper. Serve.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Rice Cakes, Jam & Protein Shake',
    'lean',
    'snack',
    385,
    30,
    55,
    5,
    ARRAY['vegan', 'gluten-free', 'hitt_lean_v1'],
    ARRAY['soya'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '3 rice cakes', 0),
    ((SELECT id FROM new_recipe), '20g jam', 1),
    ((SELECT id FROM new_recipe), '1 scoop (30g) soya protein', 2),
    ((SELECT id FROM new_recipe), '300ml water', 3)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Prepare and portion each component.'),
    ((SELECT id FROM new_recipe), 2, 'Assemble on a plate or in a pot.'),
    ((SELECT id FROM new_recipe), 3, 'Mix or shake any liquid element and serve alongside.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Banana Protein Flapjack',
    'lean',
    'snack',
    410,
    20,
    60,
    10,
    ARRAY['vegetarian', 'hitt_lean_v1'],
    ARRAY['gluten', 'soya'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '50g oats', 0),
    ((SELECT id FROM new_recipe), '1 banana', 1),
    ((SELECT id FROM new_recipe), '1 scoop (25g) whey', 2),
    ((SELECT id FROM new_recipe), '10g maple syrup', 3),
    ((SELECT id FROM new_recipe), 'raisins', 4)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Prepare and portion each component.'),
    ((SELECT id FROM new_recipe), 2, 'Assemble on a plate or in a pot.'),
    ((SELECT id FROM new_recipe), 3, 'Mix or shake any liquid element and serve alongside.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Mango Sorbet & Dairy-Free Protein Yogurt',
    'lean',
    'snack',
    402,
    25,
    62,
    6,
    ARRAY['vegan', 'gluten-free', 'hitt_lean_v1'],
    ARRAY['soya'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '150g mango sorbet', 0),
    ((SELECT id FROM new_recipe), '150g soya yogurt', 1),
    ((SELECT id FROM new_recipe), '1/2 scoop (15g) soya protein', 2),
    ((SELECT id FROM new_recipe), 'granola-free oats', 3)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Prepare and portion each component.'),
    ((SELECT id FROM new_recipe), 2, 'Assemble on a plate or in a pot.'),
    ((SELECT id FROM new_recipe), 3, 'Mix or shake any liquid element and serve alongside.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Bagel with Syrup & Whey',
    'lean',
    'snack',
    435,
    28,
    65,
    7,
    ARRAY['vegetarian', 'hitt_lean_v1'],
    ARRAY['gluten', 'soya'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '1 plain bagel', 0),
    ((SELECT id FROM new_recipe), '15g syrup', 1),
    ((SELECT id FROM new_recipe), '1 scoop (25g) whey', 2),
    ((SELECT id FROM new_recipe), '250ml water', 3)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Prepare and portion each component.'),
    ((SELECT id FROM new_recipe), 2, 'Assemble on a plate or in a pot.'),
    ((SELECT id FROM new_recipe), 3, 'Mix or shake any liquid element and serve alongside.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Rice Pudding with Berries',
    'lean',
    'snack',
    440,
    22,
    70,
    8,
    ARRAY['vegan', 'gluten-free', 'hitt_lean_v1'],
    ARRAY['soya'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '200g dairy-free rice pudding', 0),
    ((SELECT id FROM new_recipe), '80g berries', 1),
    ((SELECT id FROM new_recipe), '1/2 scoop (15g) soya protein', 2),
    ((SELECT id FROM new_recipe), 'cinnamon', 3)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Prepare and portion each component.'),
    ((SELECT id FROM new_recipe), 2, 'Assemble on a plate or in a pot.'),
    ((SELECT id FROM new_recipe), 3, 'Mix or shake any liquid element and serve alongside.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Pretzels, Hummus & Protein Shake',
    'lean',
    'snack',
    434,
    26,
    60,
    10,
    ARRAY['vegan', 'hitt_lean_v1'],
    ARRAY['gluten', 'sesame', 'soya'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '50g pretzels', 0),
    ((SELECT id FROM new_recipe), '60g hummus', 1),
    ((SELECT id FROM new_recipe), '1 scoop (30g) soya protein', 2),
    ((SELECT id FROM new_recipe), '300ml water', 3)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Prepare and portion each component.'),
    ((SELECT id FROM new_recipe), 2, 'Assemble on a plate or in a pot.'),
    ((SELECT id FROM new_recipe), 3, 'Mix or shake any liquid element and serve alongside.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Dried Fruit & Rice Cake Energy Plate',
    'lean',
    'snack',
    434,
    20,
    75,
    6,
    ARRAY['vegan', 'gluten-free', 'hitt_lean_v1'],
    ARRAY['soya'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '3 rice cakes', 0),
    ((SELECT id FROM new_recipe), '40g dried apricots & raisins', 1),
    ((SELECT id FROM new_recipe), '1/2 scoop (15g) soya protein shake', 2)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Prepare and portion each component.'),
    ((SELECT id FROM new_recipe), 2, 'Assemble on a plate or in a pot.'),
    ((SELECT id FROM new_recipe), 3, 'Mix or shake any liquid element and serve alongside.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Tuna & Cracker Protein Box',
    'lean',
    'snack',
    400,
    32,
    50,
    8,
    ARRAY['hitt_lean_v1'],
    ARRAY['fish', 'gluten'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '1 tin tuna in spring water', 0),
    ((SELECT id FROM new_recipe), '6 crackers', 1),
    ((SELECT id FROM new_recipe), 'cherry tomatoes', 2),
    ((SELECT id FROM new_recipe), 'black pepper', 3)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Prepare and portion each component.'),
    ((SELECT id FROM new_recipe), 2, 'Assemble on a plate or in a pot.'),
    ((SELECT id FROM new_recipe), 3, 'Mix or shake any liquid element and serve alongside.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Oat & Berry Protein Smoothie',
    'lean',
    'snack',
    415,
    30,
    58,
    7,
    ARRAY['vegan', 'hitt_lean_v1'],
    ARRAY['gluten', 'soya'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '30g oats', 0),
    ((SELECT id FROM new_recipe), '150g berries', 1),
    ((SELECT id FROM new_recipe), '1 scoop (30g) soya protein', 2),
    ((SELECT id FROM new_recipe), '300ml water', 3)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Add all ingredients to a blender with a handful of ice.'),
    ((SELECT id FROM new_recipe), 2, 'Blend on high until completely smooth.'),
    ((SELECT id FROM new_recipe), 3, 'Pour into a glass or bowl; add the toppings if serving as a bowl.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Sushi-Style Rice & Edamame',
    'lean',
    'snack',
    419,
    24,
    65,
    7,
    ARRAY['vegan', 'gluten-free', 'hitt_lean_v1'],
    ARRAY['soya', 'sesame'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '180g sushi rice', 0),
    ((SELECT id FROM new_recipe), '80g edamame', 1),
    ((SELECT id FROM new_recipe), 'nori & sesame', 2),
    ((SELECT id FROM new_recipe), 'rice vinegar', 3)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Prepare and portion each component.'),
    ((SELECT id FROM new_recipe), 2, 'Assemble on a plate or in a pot.'),
    ((SELECT id FROM new_recipe), 3, 'Mix or shake any liquid element and serve alongside.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Jacket Potato & Baked Beans',
    'lean',
    'snack',
    445,
    22,
    78,
    5,
    ARRAY['vegan', 'gluten-free', 'hitt_lean_v1'],
    ARRAY[]::TEXT[],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '1 large jacket potato', 0),
    ((SELECT id FROM new_recipe), '200g baked beans', 1),
    ((SELECT id FROM new_recipe), 'chives', 2),
    ((SELECT id FROM new_recipe), 'black pepper', 3)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Heat the oven to 200°C. Spread the protein and vegetables on a lined tray.'),
    ((SELECT id FROM new_recipe), 2, 'Season, spray lightly with oil, and add the potato or grain.'),
    ((SELECT id FROM new_recipe), 3, 'Roast 20-25 minutes until cooked through and golden.'),
    ((SELECT id FROM new_recipe), 4, 'Plate up and finish with fresh herbs. Serve.');

COMMIT;