-- Auto-generated by scripts/gen_veg_df_keto_pack.ts
-- 30-recipe vegetarian + dairy-free keto extension pack.
-- Tagged with 'hitt_ext_v1' in dietary_tags for later replacement.
-- Idempotent: re-running this seed replaces only these rows.

BEGIN;

-- Cascade deletes ingredients + steps via FK ON DELETE CASCADE.
DELETE FROM public.recipes WHERE source = 'owner' AND category = 'keto'
  AND dietary_tags @> ARRAY['hitt_ext_v1']::TEXT[];

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Asian-inspired Firm Tofu with Cauliflower Rice & Baby Spinach',
    'keto',
    'lunch',
    400,
    30,
    13,
    27,
    ARRAY['vegetarian', 'gluten-free', 'hitt_ext_v1'],
    ARRAY['soy', 'sesame'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '150g firm tofu', 0),
    ((SELECT id FROM new_recipe), '100g cauliflower rice', 1),
    ((SELECT id FROM new_recipe), '100g baby spinach', 2),
    ((SELECT id FROM new_recipe), '10g sesame oil', 3),
    ((SELECT id FROM new_recipe), '15g hemp seeds', 4),
    ((SELECT id FROM new_recipe), 'tamari (gluten-free soy), ginger and spring onion', 5),
    ((SELECT id FROM new_recipe), 'Salt and black pepper, to taste', 6)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Press and cube the firm tofu.'),
    ((SELECT id FROM new_recipe), 2, 'Season the firm tofu generously with tamari, ginger and spring onion.'),
    ((SELECT id FROM new_recipe), 3, 'Cook the firm tofu pan-seared in a little olive oil until golden on all sides.'),
    ((SELECT id FROM new_recipe), 4, 'Meanwhile, prepare the cauliflower rice by sautéing in a hot pan with a little fat for 4-5 minutes.'),
    ((SELECT id FROM new_recipe), 5, 'Steam or sauté the baby spinach for 3-4 minutes until just tender but still vibrant.'),
    ((SELECT id FROM new_recipe), 6, 'Plate the cauliflower rice as a base, top with the firm tofu and baby spinach.'),
    ((SELECT id FROM new_recipe), 7, 'Finish with the sesame oil and hemp seeds and a final crack of black pepper. Serve immediately.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Mediterranean Firm Tofu with Cabbage (Shredded) & Olives',
    'keto',
    'lunch',
    420,
    27,
    12,
    30,
    ARRAY['vegetarian', 'gluten-free', 'hitt_ext_v1'],
    ARRAY['soy'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '150g firm tofu', 0),
    ((SELECT id FROM new_recipe), '100g shredded cabbage', 1),
    ((SELECT id FROM new_recipe), '100g mixed salad leaves', 2),
    ((SELECT id FROM new_recipe), '15g olive oil', 3),
    ((SELECT id FROM new_recipe), '25g olives (pitted)', 4),
    ((SELECT id FROM new_recipe), 'oregano, basil and a squeeze of lemon', 5),
    ((SELECT id FROM new_recipe), 'Salt and black pepper, to taste', 6)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Press and cube the firm tofu.'),
    ((SELECT id FROM new_recipe), 2, 'Season the firm tofu generously with oregano, basil and a squeeze of lemon.'),
    ((SELECT id FROM new_recipe), 3, 'Cook the firm tofu pan-seared in a little olive oil until golden on all sides.'),
    ((SELECT id FROM new_recipe), 4, 'Meanwhile, prepare the shredded cabbage by sautéing in a hot pan with a little fat for 4-5 minutes.'),
    ((SELECT id FROM new_recipe), 5, 'Steam or sauté the mixed salad leaves for 3-4 minutes until just tender but still vibrant.'),
    ((SELECT id FROM new_recipe), 6, 'Plate the shredded cabbage as a base, top with the firm tofu and mixed salad leaves.'),
    ((SELECT id FROM new_recipe), 7, 'Finish with the olive oil and olives and a final crack of black pepper. Serve immediately.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Italian herb Whole Eggs with Broccoli Florets & Cherry Tomatoes',
    'keto',
    'lunch',
    460,
    25,
    12,
    35,
    ARRAY['vegetarian', 'gluten-free', 'hitt_ext_v1'],
    ARRAY['eggs'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '3 whole eggs', 0),
    ((SELECT id FROM new_recipe), '100g broccoli florets', 1),
    ((SELECT id FROM new_recipe), '80g cherry tomatoes', 2),
    ((SELECT id FROM new_recipe), '15g olive oil', 3),
    ((SELECT id FROM new_recipe), '20g pumpkin seeds', 4),
    ((SELECT id FROM new_recipe), 'basil, oregano and a touch of chilli flake', 5),
    ((SELECT id FROM new_recipe), 'Salt and black pepper, to taste', 6)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Whisk the whole eggs lightly in a bowl.'),
    ((SELECT id FROM new_recipe), 2, 'Season the whole eggs generously with basil, oregano and a touch of chilli flake.'),
    ((SELECT id FROM new_recipe), 3, 'Cook the whole eggs scrambled in a non-stick pan over medium heat until just set.'),
    ((SELECT id FROM new_recipe), 4, 'Meanwhile, prepare the broccoli florets by sautéing in a hot pan with a little fat for 4-5 minutes.'),
    ((SELECT id FROM new_recipe), 5, 'Steam or sauté the cherry tomatoes for 3-4 minutes until just tender but still vibrant.'),
    ((SELECT id FROM new_recipe), 6, 'Plate the broccoli florets as a base, top with the whole eggs and cherry tomatoes.'),
    ((SELECT id FROM new_recipe), 7, 'Finish with the olive oil and pumpkin seeds and a final crack of black pepper. Serve immediately.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Moroccan-spiced Firm Tofu with Courgette Noodles (Zoodles) & Kale',
    'keto',
    'lunch',
    395,
    28,
    11,
    26,
    ARRAY['vegetarian', 'gluten-free', 'hitt_ext_v1'],
    ARRAY['soy'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '150g firm tofu', 0),
    ((SELECT id FROM new_recipe), '100g courgette noodles (zoodles)', 1),
    ((SELECT id FROM new_recipe), '100g kale', 2),
    ((SELECT id FROM new_recipe), '15g olive oil', 3),
    ((SELECT id FROM new_recipe), '20g sunflower seeds', 4),
    ((SELECT id FROM new_recipe), 'ras el hanout, cumin and cinnamon', 5),
    ((SELECT id FROM new_recipe), 'Salt and black pepper, to taste', 6)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Press and cube the firm tofu.'),
    ((SELECT id FROM new_recipe), 2, 'Season the firm tofu generously with ras el hanout, cumin and cinnamon.'),
    ((SELECT id FROM new_recipe), 3, 'Cook the firm tofu pan-seared in a little olive oil until golden on all sides.'),
    ((SELECT id FROM new_recipe), 4, 'Meanwhile, prepare the courgette noodles (zoodles) by sautéing in a hot pan with a little fat for 4-5 minutes.'),
    ((SELECT id FROM new_recipe), 5, 'Steam or sauté the kale for 3-4 minutes until just tender but still vibrant.'),
    ((SELECT id FROM new_recipe), 6, 'Plate the courgette noodles (zoodles) as a base, top with the firm tofu and kale.'),
    ((SELECT id FROM new_recipe), 7, 'Finish with the olive oil and sunflower seeds and a final crack of black pepper. Serve immediately.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Peri-peri Egg Whites with Cauliflower Rice & Mixed Peppers',
    'keto',
    'lunch',
    380,
    30,
    11,
    24,
    ARRAY['vegetarian', 'gluten-free', 'hitt_ext_v1'],
    ARRAY['eggs'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '200g egg whites', 0),
    ((SELECT id FROM new_recipe), '100g cauliflower rice', 1),
    ((SELECT id FROM new_recipe), '100g mixed peppers', 2),
    ((SELECT id FROM new_recipe), '15g olive oil', 3),
    ((SELECT id FROM new_recipe), '60g avocado', 4),
    ((SELECT id FROM new_recipe), 'peri-peri seasoning and a squeeze of lime', 5),
    ((SELECT id FROM new_recipe), 'Salt and black pepper, to taste', 6)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Whisk the egg whites lightly in a bowl.'),
    ((SELECT id FROM new_recipe), 2, 'Season the egg whites generously with peri-peri seasoning and a squeeze of lime.'),
    ((SELECT id FROM new_recipe), 3, 'Cook the egg whites scrambled in a non-stick pan over medium heat until just set.'),
    ((SELECT id FROM new_recipe), 4, 'Meanwhile, prepare the cauliflower rice by sautéing in a hot pan with a little fat for 4-5 minutes.'),
    ((SELECT id FROM new_recipe), 5, 'Steam or sauté the mixed peppers for 3-4 minutes until just tender but still vibrant.'),
    ((SELECT id FROM new_recipe), 6, 'Plate the cauliflower rice as a base, top with the egg whites and mixed peppers.'),
    ((SELECT id FROM new_recipe), 7, 'Finish with the olive oil and sliced avocado and a final crack of black pepper. Serve immediately.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Cajun Firm Tofu with Broccoli Florets & Red Onion',
    'keto',
    'lunch',
    440,
    29,
    13,
    30,
    ARRAY['vegetarian', 'gluten-free', 'hitt_ext_v1'],
    ARRAY['soy'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '150g firm tofu', 0),
    ((SELECT id FROM new_recipe), '100g broccoli florets', 1),
    ((SELECT id FROM new_recipe), '60g red onion', 2),
    ((SELECT id FROM new_recipe), '15g olive oil', 3),
    ((SELECT id FROM new_recipe), '20g walnuts', 4),
    ((SELECT id FROM new_recipe), 'Cajun seasoning, smoked paprika and garlic powder', 5),
    ((SELECT id FROM new_recipe), 'Salt and black pepper, to taste', 6)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Press and cube the firm tofu.'),
    ((SELECT id FROM new_recipe), 2, 'Season the firm tofu generously with Cajun seasoning, smoked paprika and garlic powder.'),
    ((SELECT id FROM new_recipe), 3, 'Cook the firm tofu pan-seared in a little olive oil until golden on all sides.'),
    ((SELECT id FROM new_recipe), 4, 'Meanwhile, prepare the broccoli florets by sautéing in a hot pan with a little fat for 4-5 minutes.'),
    ((SELECT id FROM new_recipe), 5, 'Steam or sauté the red onion for 3-4 minutes until just tender but still vibrant.'),
    ((SELECT id FROM new_recipe), 6, 'Plate the broccoli florets as a base, top with the firm tofu and red onion.'),
    ((SELECT id FROM new_recipe), 7, 'Finish with the olive oil and walnuts and a final crack of black pepper. Serve immediately.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Garlic & chilli Whole Eggs with Cabbage (Shredded) & Baby Spinach',
    'keto',
    'lunch',
    485,
    25,
    10,
    38,
    ARRAY['vegetarian', 'gluten-free', 'hitt_ext_v1'],
    ARRAY['eggs'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '3 whole eggs', 0),
    ((SELECT id FROM new_recipe), '100g shredded cabbage', 1),
    ((SELECT id FROM new_recipe), '80g baby spinach', 2),
    ((SELECT id FROM new_recipe), '15g olive oil', 3),
    ((SELECT id FROM new_recipe), '80g avocado', 4),
    ((SELECT id FROM new_recipe), 'crushed garlic, chilli flakes and parsley', 5),
    ((SELECT id FROM new_recipe), 'Salt and black pepper, to taste', 6)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Whisk the whole eggs lightly in a bowl.'),
    ((SELECT id FROM new_recipe), 2, 'Season the whole eggs generously with crushed garlic, chilli flakes and parsley.'),
    ((SELECT id FROM new_recipe), 3, 'Cook the whole eggs scrambled in a non-stick pan over medium heat until just set.'),
    ((SELECT id FROM new_recipe), 4, 'Meanwhile, prepare the shredded cabbage by sautéing in a hot pan with a little fat for 4-5 minutes.'),
    ((SELECT id FROM new_recipe), 5, 'Steam or sauté the baby spinach for 3-4 minutes until just tender but still vibrant.'),
    ((SELECT id FROM new_recipe), 6, 'Plate the shredded cabbage as a base, top with the whole eggs and baby spinach.'),
    ((SELECT id FROM new_recipe), 7, 'Finish with the olive oil and sliced avocado and a final crack of black pepper. Serve immediately.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Teriyaki Firm Tofu with Courgette Noodles (Zoodles) & Asparagus Tips',
    'keto',
    'lunch',
    390,
    28,
    13,
    25,
    ARRAY['vegetarian', 'gluten-free', 'hitt_ext_v1'],
    ARRAY['soy', 'sesame'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '150g firm tofu', 0),
    ((SELECT id FROM new_recipe), '100g courgette noodles (zoodles)', 1),
    ((SELECT id FROM new_recipe), '100g asparagus tips', 2),
    ((SELECT id FROM new_recipe), '10g sesame oil', 3),
    ((SELECT id FROM new_recipe), '15g tahini', 4),
    ((SELECT id FROM new_recipe), 'tamari (gluten-free soy), ginger and mirin', 5),
    ((SELECT id FROM new_recipe), 'Salt and black pepper, to taste', 6)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Press and cube the firm tofu.'),
    ((SELECT id FROM new_recipe), 2, 'Season the firm tofu generously with tamari, ginger and mirin.'),
    ((SELECT id FROM new_recipe), 3, 'Cook the firm tofu pan-seared in a little olive oil until golden on all sides.'),
    ((SELECT id FROM new_recipe), 4, 'Meanwhile, prepare the courgette noodles (zoodles) by sautéing in a hot pan with a little fat for 4-5 minutes.'),
    ((SELECT id FROM new_recipe), 5, 'Steam or sauté the asparagus tips for 3-4 minutes until just tender but still vibrant.'),
    ((SELECT id FROM new_recipe), 6, 'Plate the courgette noodles (zoodles) as a base, top with the firm tofu and asparagus tips.'),
    ((SELECT id FROM new_recipe), 7, 'Finish with the sesame oil and tahini and a final crack of black pepper. Serve immediately.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Lemon herb Egg Whites with Cauliflower Rice & Chestnut Mushrooms',
    'keto',
    'lunch',
    360,
    27,
    9,
    23,
    ARRAY['vegetarian', 'gluten-free', 'hitt_ext_v1'],
    ARRAY['eggs'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '200g egg whites', 0),
    ((SELECT id FROM new_recipe), '100g cauliflower rice', 1),
    ((SELECT id FROM new_recipe), '100g chestnut mushrooms', 2),
    ((SELECT id FROM new_recipe), '15g olive oil', 3),
    ((SELECT id FROM new_recipe), '60g avocado', 4),
    ((SELECT id FROM new_recipe), 'lemon juice, thyme and rosemary', 5),
    ((SELECT id FROM new_recipe), 'Salt and black pepper, to taste', 6)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Whisk the egg whites lightly in a bowl.'),
    ((SELECT id FROM new_recipe), 2, 'Season the egg whites generously with lemon juice, thyme and rosemary.'),
    ((SELECT id FROM new_recipe), 3, 'Cook the egg whites scrambled in a non-stick pan over medium heat until just set.'),
    ((SELECT id FROM new_recipe), 4, 'Meanwhile, prepare the cauliflower rice by sautéing in a hot pan with a little fat for 4-5 minutes.'),
    ((SELECT id FROM new_recipe), 5, 'Steam or sauté the chestnut mushrooms for 3-4 minutes until just tender but still vibrant.'),
    ((SELECT id FROM new_recipe), 6, 'Plate the cauliflower rice as a base, top with the egg whites and chestnut mushrooms.'),
    ((SELECT id FROM new_recipe), 7, 'Finish with the olive oil and sliced avocado and a final crack of black pepper. Serve immediately.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Indian-spiced Firm Tofu with Cabbage (Shredded) & Cherry Tomatoes',
    'keto',
    'lunch',
    415,
    27,
    13,
    28,
    ARRAY['vegetarian', 'gluten-free', 'hitt_ext_v1'],
    ARRAY['soy'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '150g firm tofu', 0),
    ((SELECT id FROM new_recipe), '100g shredded cabbage', 1),
    ((SELECT id FROM new_recipe), '80g cherry tomatoes', 2),
    ((SELECT id FROM new_recipe), '15g olive oil', 3),
    ((SELECT id FROM new_recipe), '15g coconut cream', 4),
    ((SELECT id FROM new_recipe), 'garam masala, turmeric and cumin', 5),
    ((SELECT id FROM new_recipe), 'Salt and black pepper, to taste', 6)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Press and cube the firm tofu.'),
    ((SELECT id FROM new_recipe), 2, 'Season the firm tofu generously with garam masala, turmeric and cumin.'),
    ((SELECT id FROM new_recipe), 3, 'Cook the firm tofu pan-seared in a little olive oil until golden on all sides.'),
    ((SELECT id FROM new_recipe), 4, 'Meanwhile, prepare the shredded cabbage by sautéing in a hot pan with a little fat for 4-5 minutes.'),
    ((SELECT id FROM new_recipe), 5, 'Steam or sauté the cherry tomatoes for 3-4 minutes until just tender but still vibrant.'),
    ((SELECT id FROM new_recipe), 6, 'Plate the shredded cabbage as a base, top with the firm tofu and cherry tomatoes.'),
    ((SELECT id FROM new_recipe), 7, 'Finish with the olive oil and coconut cream and a final crack of black pepper. Serve immediately.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Mediterranean Firm Tofu with Courgette Noodles (Zoodles) & Olives',
    'keto',
    'dinner',
    580,
    32,
    13,
    44,
    ARRAY['vegetarian', 'gluten-free', 'hitt_ext_v1'],
    ARRAY['soy'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '180g firm tofu', 0),
    ((SELECT id FROM new_recipe), '100g courgette noodles (zoodles)', 1),
    ((SELECT id FROM new_recipe), '100g mixed salad leaves', 2),
    ((SELECT id FROM new_recipe), '20g olive oil', 3),
    ((SELECT id FROM new_recipe), '40g olives (pitted)', 4),
    ((SELECT id FROM new_recipe), '80g avocado', 5),
    ((SELECT id FROM new_recipe), 'oregano, basil and a squeeze of lemon', 6),
    ((SELECT id FROM new_recipe), 'Salt and black pepper, to taste', 7)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Press and cube the firm tofu.'),
    ((SELECT id FROM new_recipe), 2, 'Season the firm tofu generously with oregano, basil and a squeeze of lemon.'),
    ((SELECT id FROM new_recipe), 3, 'Cook the firm tofu pan-seared in a little olive oil until golden on all sides.'),
    ((SELECT id FROM new_recipe), 4, 'Meanwhile, prepare the courgette noodles (zoodles) by sautéing in a hot pan with a little fat for 4-5 minutes.'),
    ((SELECT id FROM new_recipe), 5, 'Steam or sauté the mixed salad leaves for 3-4 minutes until just tender but still vibrant.'),
    ((SELECT id FROM new_recipe), 6, 'Plate the courgette noodles (zoodles) as a base, top with the firm tofu and mixed salad leaves.'),
    ((SELECT id FROM new_recipe), 7, 'Finish with the olive oil, olives and sliced avocado and a final crack of black pepper. Serve immediately.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Moroccan-spiced Tempeh with Cauliflower Rice & Kale',
    'keto',
    'dinner',
    605,
    34,
    14,
    42,
    ARRAY['vegetarian', 'gluten-free', 'hitt_ext_v1'],
    ARRAY['soy'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '150g tempeh', 0),
    ((SELECT id FROM new_recipe), '100g cauliflower rice', 1),
    ((SELECT id FROM new_recipe), '100g kale', 2),
    ((SELECT id FROM new_recipe), '20g olive oil', 3),
    ((SELECT id FROM new_recipe), '20g sunflower seeds', 4),
    ((SELECT id FROM new_recipe), '80g avocado', 5),
    ((SELECT id FROM new_recipe), 'ras el hanout, cumin and cinnamon', 6),
    ((SELECT id FROM new_recipe), 'Salt and black pepper, to taste', 7)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Slice the tempeh into thin strips.'),
    ((SELECT id FROM new_recipe), 2, 'Season the tempeh generously with ras el hanout, cumin and cinnamon.'),
    ((SELECT id FROM new_recipe), 3, 'Cook the tempeh pan-seared in a little olive oil until golden and heated through, turning once.'),
    ((SELECT id FROM new_recipe), 4, 'Meanwhile, prepare the cauliflower rice by sautéing in a hot pan with a little fat for 4-5 minutes.'),
    ((SELECT id FROM new_recipe), 5, 'Steam or sauté the kale for 3-4 minutes until just tender but still vibrant.'),
    ((SELECT id FROM new_recipe), 6, 'Plate the cauliflower rice as a base, top with the tempeh and kale.'),
    ((SELECT id FROM new_recipe), 7, 'Finish with the olive oil, sunflower seeds and sliced avocado and a final crack of black pepper. Serve immediately.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Cajun Whole Eggs with Broccoli Florets & Chestnut Mushrooms',
    'keto',
    'dinner',
    560,
    28,
    11,
    44,
    ARRAY['vegetarian', 'gluten-free', 'hitt_ext_v1'],
    ARRAY['eggs'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '4 whole eggs', 0),
    ((SELECT id FROM new_recipe), '100g broccoli florets', 1),
    ((SELECT id FROM new_recipe), '100g chestnut mushrooms', 2),
    ((SELECT id FROM new_recipe), '20g olive oil', 3),
    ((SELECT id FROM new_recipe), '80g avocado', 4),
    ((SELECT id FROM new_recipe), '20g pumpkin seeds', 5),
    ((SELECT id FROM new_recipe), 'Cajun seasoning, smoked paprika and garlic powder', 6),
    ((SELECT id FROM new_recipe), 'Salt and black pepper, to taste', 7)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Whisk the whole eggs lightly in a bowl.'),
    ((SELECT id FROM new_recipe), 2, 'Season the whole eggs generously with Cajun seasoning, smoked paprika and garlic powder.'),
    ((SELECT id FROM new_recipe), 3, 'Cook the whole eggs scrambled in a non-stick pan over medium heat until just set.'),
    ((SELECT id FROM new_recipe), 4, 'Meanwhile, prepare the broccoli florets by sautéing in a hot pan with a little fat for 4-5 minutes.'),
    ((SELECT id FROM new_recipe), 5, 'Steam or sauté the chestnut mushrooms for 3-4 minutes until just tender but still vibrant.'),
    ((SELECT id FROM new_recipe), 6, 'Plate the broccoli florets as a base, top with the whole eggs and chestnut mushrooms.'),
    ((SELECT id FROM new_recipe), 7, 'Finish with the olive oil, sliced avocado and pumpkin seeds and a final crack of black pepper. Serve immediately.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Italian herb Firm Tofu with Cabbage (Shredded) & Cherry Tomatoes',
    'keto',
    'dinner',
    630,
    33,
    13,
    48,
    ARRAY['vegetarian', 'gluten-free', 'hitt_ext_v1'],
    ARRAY['soy'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '180g firm tofu', 0),
    ((SELECT id FROM new_recipe), '100g shredded cabbage', 1),
    ((SELECT id FROM new_recipe), '80g cherry tomatoes', 2),
    ((SELECT id FROM new_recipe), '20g olive oil', 3),
    ((SELECT id FROM new_recipe), '30g olives (pitted)', 4),
    ((SELECT id FROM new_recipe), '80g avocado', 5),
    ((SELECT id FROM new_recipe), 'basil, oregano and a touch of chilli flake', 6),
    ((SELECT id FROM new_recipe), 'Salt and black pepper, to taste', 7)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Press and cube the firm tofu.'),
    ((SELECT id FROM new_recipe), 2, 'Season the firm tofu generously with basil, oregano and a touch of chilli flake.'),
    ((SELECT id FROM new_recipe), 3, 'Cook the firm tofu pan-seared in a little olive oil until golden on all sides.'),
    ((SELECT id FROM new_recipe), 4, 'Meanwhile, prepare the shredded cabbage by sautéing in a hot pan with a little fat for 4-5 minutes.'),
    ((SELECT id FROM new_recipe), 5, 'Steam or sauté the cherry tomatoes for 3-4 minutes until just tender but still vibrant.'),
    ((SELECT id FROM new_recipe), 6, 'Plate the shredded cabbage as a base, top with the firm tofu and cherry tomatoes.'),
    ((SELECT id FROM new_recipe), 7, 'Finish with the olive oil, olives and sliced avocado and a final crack of black pepper. Serve immediately.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Asian-inspired Tempeh with Courgette Noodles (Zoodles) & Baby Spinach',
    'keto',
    'dinner',
    585,
    34,
    14,
    41,
    ARRAY['vegetarian', 'gluten-free', 'hitt_ext_v1'],
    ARRAY['soy', 'sesame'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '150g tempeh', 0),
    ((SELECT id FROM new_recipe), '100g courgette noodles (zoodles)', 1),
    ((SELECT id FROM new_recipe), '100g baby spinach', 2),
    ((SELECT id FROM new_recipe), '10g sesame oil', 3),
    ((SELECT id FROM new_recipe), '15g tahini', 4),
    ((SELECT id FROM new_recipe), '20g hemp seeds', 5),
    ((SELECT id FROM new_recipe), 'tamari (gluten-free soy), ginger and spring onion', 6),
    ((SELECT id FROM new_recipe), 'Salt and black pepper, to taste', 7)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Slice the tempeh into thin strips.'),
    ((SELECT id FROM new_recipe), 2, 'Season the tempeh generously with tamari, ginger and spring onion.'),
    ((SELECT id FROM new_recipe), 3, 'Cook the tempeh pan-seared in a little olive oil until golden and heated through, turning once.'),
    ((SELECT id FROM new_recipe), 4, 'Meanwhile, prepare the courgette noodles (zoodles) by sautéing in a hot pan with a little fat for 4-5 minutes.'),
    ((SELECT id FROM new_recipe), 5, 'Steam or sauté the baby spinach for 3-4 minutes until just tender but still vibrant.'),
    ((SELECT id FROM new_recipe), 6, 'Plate the courgette noodles (zoodles) as a base, top with the tempeh and baby spinach.'),
    ((SELECT id FROM new_recipe), 7, 'Finish with the sesame oil, tahini and hemp seeds and a final crack of black pepper. Serve immediately.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Peri-peri Firm Tofu with Cauliflower Rice & Asparagus Tips',
    'keto',
    'dinner',
    620,
    33,
    12,
    48,
    ARRAY['vegetarian', 'gluten-free', 'hitt_ext_v1'],
    ARRAY['soy'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '180g firm tofu', 0),
    ((SELECT id FROM new_recipe), '100g cauliflower rice', 1),
    ((SELECT id FROM new_recipe), '100g asparagus tips', 2),
    ((SELECT id FROM new_recipe), '20g olive oil', 3),
    ((SELECT id FROM new_recipe), '80g avocado', 4),
    ((SELECT id FROM new_recipe), '20g pumpkin seeds', 5),
    ((SELECT id FROM new_recipe), 'peri-peri seasoning and a squeeze of lime', 6),
    ((SELECT id FROM new_recipe), 'Salt and black pepper, to taste', 7)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Press and cube the firm tofu.'),
    ((SELECT id FROM new_recipe), 2, 'Season the firm tofu generously with peri-peri seasoning and a squeeze of lime.'),
    ((SELECT id FROM new_recipe), 3, 'Cook the firm tofu pan-seared in a little olive oil until golden on all sides.'),
    ((SELECT id FROM new_recipe), 4, 'Meanwhile, prepare the cauliflower rice by sautéing in a hot pan with a little fat for 4-5 minutes.'),
    ((SELECT id FROM new_recipe), 5, 'Steam or sauté the asparagus tips for 3-4 minutes until just tender but still vibrant.'),
    ((SELECT id FROM new_recipe), 6, 'Plate the cauliflower rice as a base, top with the firm tofu and asparagus tips.'),
    ((SELECT id FROM new_recipe), 7, 'Finish with the olive oil, sliced avocado and pumpkin seeds and a final crack of black pepper. Serve immediately.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Teriyaki Egg Whites with Cauliflower Rice & Tenderstem Broccoli',
    'keto',
    'dinner',
    545,
    30,
    12,
    40,
    ARRAY['vegetarian', 'gluten-free', 'hitt_ext_v1'],
    ARRAY['eggs', 'soy', 'sesame'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '220g egg whites', 0),
    ((SELECT id FROM new_recipe), '100g cauliflower rice', 1),
    ((SELECT id FROM new_recipe), '100g tenderstem broccoli', 2),
    ((SELECT id FROM new_recipe), '10g sesame oil', 3),
    ((SELECT id FROM new_recipe), '80g avocado', 4),
    ((SELECT id FROM new_recipe), '20g hemp seeds', 5),
    ((SELECT id FROM new_recipe), 'tamari (gluten-free soy), ginger and mirin', 6),
    ((SELECT id FROM new_recipe), 'Salt and black pepper, to taste', 7)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Whisk the egg whites lightly in a bowl.'),
    ((SELECT id FROM new_recipe), 2, 'Season the egg whites generously with tamari, ginger and mirin.'),
    ((SELECT id FROM new_recipe), 3, 'Cook the egg whites scrambled in a non-stick pan over medium heat until just set.'),
    ((SELECT id FROM new_recipe), 4, 'Meanwhile, prepare the cauliflower rice by sautéing in a hot pan with a little fat for 4-5 minutes.'),
    ((SELECT id FROM new_recipe), 5, 'Steam or sauté the tenderstem broccoli for 3-4 minutes until just tender but still vibrant.'),
    ((SELECT id FROM new_recipe), 6, 'Plate the cauliflower rice as a base, top with the egg whites and tenderstem broccoli.'),
    ((SELECT id FROM new_recipe), 7, 'Finish with the sesame oil, sliced avocado and hemp seeds and a final crack of black pepper. Serve immediately.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'BBQ Firm Tofu with Broccoli Florets & Red Onion',
    'keto',
    'dinner',
    590,
    31,
    13,
    44,
    ARRAY['vegetarian', 'gluten-free', 'hitt_ext_v1'],
    ARRAY['soy'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '180g firm tofu', 0),
    ((SELECT id FROM new_recipe), '100g broccoli florets', 1),
    ((SELECT id FROM new_recipe), '60g red onion', 2),
    ((SELECT id FROM new_recipe), '20g olive oil', 3),
    ((SELECT id FROM new_recipe), '80g avocado', 4),
    ((SELECT id FROM new_recipe), '20g sunflower seeds', 5),
    ((SELECT id FROM new_recipe), 'smoked paprika, garlic powder and a smoky BBQ rub', 6),
    ((SELECT id FROM new_recipe), 'Salt and black pepper, to taste', 7)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Press and cube the firm tofu.'),
    ((SELECT id FROM new_recipe), 2, 'Season the firm tofu generously with smoked paprika, garlic powder and a smoky BBQ rub.'),
    ((SELECT id FROM new_recipe), 3, 'Cook the firm tofu pan-seared in a little olive oil until golden on all sides.'),
    ((SELECT id FROM new_recipe), 4, 'Meanwhile, prepare the broccoli florets by sautéing in a hot pan with a little fat for 4-5 minutes.'),
    ((SELECT id FROM new_recipe), 5, 'Steam or sauté the red onion for 3-4 minutes until just tender but still vibrant.'),
    ((SELECT id FROM new_recipe), 6, 'Plate the broccoli florets as a base, top with the firm tofu and red onion.'),
    ((SELECT id FROM new_recipe), 7, 'Finish with the olive oil, sliced avocado and sunflower seeds and a final crack of black pepper. Serve immediately.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Peri-peri Egg Whites with Cucumber & Olives',
    'keto',
    'snack',
    230,
    17,
    6,
    15,
    ARRAY['vegetarian', 'gluten-free', 'hitt_ext_v1'],
    ARRAY['eggs'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '120g egg whites', 0),
    ((SELECT id FROM new_recipe), '80g cucumber', 1),
    ((SELECT id FROM new_recipe), '20g olives (pitted)', 2),
    ((SELECT id FROM new_recipe), '10g olive oil', 3),
    ((SELECT id FROM new_recipe), 'peri-peri seasoning and a squeeze of lime', 4),
    ((SELECT id FROM new_recipe), 'Salt and black pepper, to taste', 5)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Season the egg whites generously with peri-peri seasoning and a squeeze of lime.'),
    ((SELECT id FROM new_recipe), 2, 'Cook the egg whites scrambled until cooked through, turning once.'),
    ((SELECT id FROM new_recipe), 3, 'Wash and prepare the cucumber and olives, then set aside to serve fresh.'),
    ((SELECT id FROM new_recipe), 4, 'Plate the cucumber and olives, top with the egg whites.'),
    ((SELECT id FROM new_recipe), 5, 'Finish with the olive oil and a final crack of black pepper. Serve immediately.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Mediterranean Firm Tofu with Cherry Tomatoes',
    'keto',
    'snack',
    270,
    18,
    7,
    18,
    ARRAY['vegetarian', 'gluten-free', 'hitt_ext_v1'],
    ARRAY['soy'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '120g firm tofu', 0),
    ((SELECT id FROM new_recipe), '80g cherry tomatoes', 1),
    ((SELECT id FROM new_recipe), '10g olive oil', 2),
    ((SELECT id FROM new_recipe), '10g olives (pitted)', 3),
    ((SELECT id FROM new_recipe), 'oregano, basil and a squeeze of lemon', 4),
    ((SELECT id FROM new_recipe), 'Salt and black pepper, to taste', 5)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Season the firm tofu generously with oregano, basil and a squeeze of lemon.'),
    ((SELECT id FROM new_recipe), 2, 'Cook the firm tofu pan-seared until cooked through, turning once.'),
    ((SELECT id FROM new_recipe), 3, 'Wash and prepare the cherry tomatoes and olives, then set aside to serve fresh.'),
    ((SELECT id FROM new_recipe), 4, 'Plate the cherry tomatoes and olives, top with the firm tofu.'),
    ((SELECT id FROM new_recipe), 5, 'Finish with the olive oil and a final crack of black pepper. Serve immediately.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Garlic & chilli Whole Eggs with Baby Spinach',
    'keto',
    'snack',
    250,
    15,
    4,
    19,
    ARRAY['vegetarian', 'gluten-free', 'hitt_ext_v1'],
    ARRAY['eggs'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '2 whole eggs', 0),
    ((SELECT id FROM new_recipe), '80g baby spinach', 1),
    ((SELECT id FROM new_recipe), '10g olive oil', 2),
    ((SELECT id FROM new_recipe), '40g avocado', 3),
    ((SELECT id FROM new_recipe), 'crushed garlic, chilli flakes and parsley', 4),
    ((SELECT id FROM new_recipe), 'Salt and black pepper, to taste', 5)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Season the whole eggs generously with crushed garlic, chilli flakes and parsley.'),
    ((SELECT id FROM new_recipe), 2, 'Cook the whole eggs scrambled until cooked through, turning once.'),
    ((SELECT id FROM new_recipe), 3, 'Wash and prepare the baby spinach, then set aside to serve fresh.'),
    ((SELECT id FROM new_recipe), 4, 'Plate the baby spinach, top with the whole eggs.'),
    ((SELECT id FROM new_recipe), 5, 'Finish with the olive oil and sliced avocado and a final crack of black pepper. Serve immediately.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Asian-inspired Firm Tofu with Cucumber',
    'keto',
    'snack',
    290,
    17,
    6,
    21,
    ARRAY['vegetarian', 'gluten-free', 'hitt_ext_v1'],
    ARRAY['soy', 'sesame'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '120g firm tofu', 0),
    ((SELECT id FROM new_recipe), '80g cucumber', 1),
    ((SELECT id FROM new_recipe), '10g sesame oil', 2),
    ((SELECT id FROM new_recipe), '10g hemp seeds', 3),
    ((SELECT id FROM new_recipe), 'tamari (gluten-free soy), ginger and spring onion', 4),
    ((SELECT id FROM new_recipe), 'Salt and black pepper, to taste', 5)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Season the firm tofu generously with tamari, ginger and spring onion.'),
    ((SELECT id FROM new_recipe), 2, 'Cook the firm tofu pan-seared until cooked through, turning once.'),
    ((SELECT id FROM new_recipe), 3, 'Wash and prepare the cucumber, then set aside to serve fresh.'),
    ((SELECT id FROM new_recipe), 4, 'Plate the cucumber, top with the firm tofu.'),
    ((SELECT id FROM new_recipe), 5, 'Finish with the sesame oil and hemp seeds and a final crack of black pepper. Serve immediately.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Italian herb Egg Whites with Cherry Tomatoes',
    'keto',
    'snack',
    200,
    18,
    6,
    12,
    ARRAY['vegetarian', 'gluten-free', 'hitt_ext_v1'],
    ARRAY['eggs'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '150g egg whites', 0),
    ((SELECT id FROM new_recipe), '80g cherry tomatoes', 1),
    ((SELECT id FROM new_recipe), '10g olive oil', 2),
    ((SELECT id FROM new_recipe), '10g pumpkin seeds', 3),
    ((SELECT id FROM new_recipe), 'basil, oregano and a touch of chilli flake', 4),
    ((SELECT id FROM new_recipe), 'Salt and black pepper, to taste', 5)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Season the egg whites generously with basil, oregano and a touch of chilli flake.'),
    ((SELECT id FROM new_recipe), 2, 'Cook the egg whites scrambled until cooked through, turning once.'),
    ((SELECT id FROM new_recipe), 3, 'Wash and prepare the cherry tomatoes, then set aside to serve fresh.'),
    ((SELECT id FROM new_recipe), 4, 'Plate the cherry tomatoes, top with the egg whites.'),
    ((SELECT id FROM new_recipe), 5, 'Finish with the olive oil and pumpkin seeds and a final crack of black pepper. Serve immediately.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Moroccan-spiced Firm Tofu with Kale',
    'keto',
    'snack',
    310,
    19,
    8,
    22,
    ARRAY['vegetarian', 'gluten-free', 'hitt_ext_v1'],
    ARRAY['soy'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '120g firm tofu', 0),
    ((SELECT id FROM new_recipe), '80g kale', 1),
    ((SELECT id FROM new_recipe), '10g olive oil', 2),
    ((SELECT id FROM new_recipe), '10g sunflower seeds', 3),
    ((SELECT id FROM new_recipe), '40g avocado', 4),
    ((SELECT id FROM new_recipe), 'ras el hanout, cumin and cinnamon', 5),
    ((SELECT id FROM new_recipe), 'Salt and black pepper, to taste', 6)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Season the firm tofu generously with ras el hanout, cumin and cinnamon.'),
    ((SELECT id FROM new_recipe), 2, 'Cook the firm tofu pan-seared until cooked through, turning once.'),
    ((SELECT id FROM new_recipe), 3, 'Wash and prepare the kale, then set aside to serve fresh.'),
    ((SELECT id FROM new_recipe), 4, 'Plate the kale, top with the firm tofu.'),
    ((SELECT id FROM new_recipe), 5, 'Finish with the olive oil, sunflower seeds and sliced avocado and a final crack of black pepper. Serve immediately.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Cajun Whole Eggs with Mixed Peppers',
    'keto',
    'snack',
    275,
    15,
    8,
    20,
    ARRAY['vegetarian', 'gluten-free', 'hitt_ext_v1'],
    ARRAY['eggs'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '2 whole eggs', 0),
    ((SELECT id FROM new_recipe), '80g mixed peppers', 1),
    ((SELECT id FROM new_recipe), '10g olive oil', 2),
    ((SELECT id FROM new_recipe), '40g avocado', 3),
    ((SELECT id FROM new_recipe), 'Cajun seasoning, smoked paprika and garlic powder', 4),
    ((SELECT id FROM new_recipe), 'Salt and black pepper, to taste', 5)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Season the whole eggs generously with Cajun seasoning, smoked paprika and garlic powder.'),
    ((SELECT id FROM new_recipe), 2, 'Cook the whole eggs scrambled until cooked through, turning once.'),
    ((SELECT id FROM new_recipe), 3, 'Wash and prepare the mixed peppers, then set aside to serve fresh.'),
    ((SELECT id FROM new_recipe), 4, 'Plate the mixed peppers, top with the whole eggs.'),
    ((SELECT id FROM new_recipe), 5, 'Finish with the olive oil and sliced avocado and a final crack of black pepper. Serve immediately.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Lemon herb Firm Tofu with Cucumber',
    'keto',
    'snack',
    250,
    17,
    5,
    18,
    ARRAY['vegetarian', 'gluten-free', 'hitt_ext_v1'],
    ARRAY['soy'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '120g firm tofu', 0),
    ((SELECT id FROM new_recipe), '80g cucumber', 1),
    ((SELECT id FROM new_recipe), '10g olive oil', 2),
    ((SELECT id FROM new_recipe), '40g avocado', 3),
    ((SELECT id FROM new_recipe), 'lemon juice, thyme and rosemary', 4),
    ((SELECT id FROM new_recipe), 'Salt and black pepper, to taste', 5)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Season the firm tofu generously with lemon juice, thyme and rosemary.'),
    ((SELECT id FROM new_recipe), 2, 'Cook the firm tofu pan-seared until cooked through, turning once.'),
    ((SELECT id FROM new_recipe), 3, 'Wash and prepare the cucumber, then set aside to serve fresh.'),
    ((SELECT id FROM new_recipe), 4, 'Plate the cucumber, top with the firm tofu.'),
    ((SELECT id FROM new_recipe), 5, 'Finish with the olive oil and sliced avocado and a final crack of black pepper. Serve immediately.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Teriyaki Egg Whites with Asparagus Tips',
    'keto',
    'snack',
    195,
    17,
    6,
    11,
    ARRAY['vegetarian', 'gluten-free', 'hitt_ext_v1'],
    ARRAY['eggs', 'soy', 'sesame'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '150g egg whites', 0),
    ((SELECT id FROM new_recipe), '80g asparagus tips', 1),
    ((SELECT id FROM new_recipe), '10g sesame oil', 2),
    ((SELECT id FROM new_recipe), '10g hemp seeds', 3),
    ((SELECT id FROM new_recipe), 'tamari (gluten-free soy), ginger and mirin', 4),
    ((SELECT id FROM new_recipe), 'Salt and black pepper, to taste', 5)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Season the egg whites generously with tamari, ginger and mirin.'),
    ((SELECT id FROM new_recipe), 2, 'Cook the egg whites scrambled until cooked through, turning once.'),
    ((SELECT id FROM new_recipe), 3, 'Wash and prepare the asparagus tips, then set aside to serve fresh.'),
    ((SELECT id FROM new_recipe), 4, 'Plate the asparagus tips, top with the egg whites.'),
    ((SELECT id FROM new_recipe), 5, 'Finish with the sesame oil and hemp seeds and a final crack of black pepper. Serve immediately.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Indian-spiced Firm Tofu with Baby Spinach',
    'keto',
    'snack',
    305,
    19,
    7,
    22,
    ARRAY['vegetarian', 'gluten-free', 'hitt_ext_v1'],
    ARRAY['soy'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '120g firm tofu', 0),
    ((SELECT id FROM new_recipe), '80g baby spinach', 1),
    ((SELECT id FROM new_recipe), '10g olive oil', 2),
    ((SELECT id FROM new_recipe), '15g coconut cream', 3),
    ((SELECT id FROM new_recipe), '40g avocado', 4),
    ((SELECT id FROM new_recipe), 'garam masala, turmeric and cumin', 5),
    ((SELECT id FROM new_recipe), 'Salt and black pepper, to taste', 6)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Season the firm tofu generously with garam masala, turmeric and cumin.'),
    ((SELECT id FROM new_recipe), 2, 'Cook the firm tofu pan-seared until cooked through, turning once.'),
    ((SELECT id FROM new_recipe), 3, 'Wash and prepare the baby spinach, then set aside to serve fresh.'),
    ((SELECT id FROM new_recipe), 4, 'Plate the baby spinach, top with the firm tofu.'),
    ((SELECT id FROM new_recipe), 5, 'Finish with the olive oil, coconut cream and sliced avocado and a final crack of black pepper. Serve immediately.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'BBQ Whole Eggs with Red Onion',
    'keto',
    'snack',
    290,
    15,
    8,
    22,
    ARRAY['vegetarian', 'gluten-free', 'hitt_ext_v1'],
    ARRAY['eggs'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '2 whole eggs', 0),
    ((SELECT id FROM new_recipe), '60g red onion', 1),
    ((SELECT id FROM new_recipe), '10g olive oil', 2),
    ((SELECT id FROM new_recipe), '40g avocado', 3),
    ((SELECT id FROM new_recipe), '10g sunflower seeds', 4),
    ((SELECT id FROM new_recipe), 'smoked paprika, garlic powder and a smoky BBQ rub', 5),
    ((SELECT id FROM new_recipe), 'Salt and black pepper, to taste', 6)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Season the whole eggs generously with smoked paprika, garlic powder and a smoky BBQ rub.'),
    ((SELECT id FROM new_recipe), 2, 'Cook the whole eggs scrambled until cooked through, turning once.'),
    ((SELECT id FROM new_recipe), 3, 'Wash and prepare the red onion, then set aside to serve fresh.'),
    ((SELECT id FROM new_recipe), 4, 'Plate the red onion, top with the whole eggs.'),
    ((SELECT id FROM new_recipe), 5, 'Finish with the olive oil, sliced avocado and sunflower seeds and a final crack of black pepper. Serve immediately.');

WITH new_recipe AS (
  INSERT INTO public.recipes (
    name, category, meal_type, calories, protein_g, carbs_g, fat_g, dietary_tags, allergens, source
  ) VALUES (
    'Mediterranean Egg Whites with Olives',
    'keto',
    'snack',
    245,
    17,
    5,
    17,
    ARRAY['vegetarian', 'gluten-free', 'hitt_ext_v1'],
    ARRAY['eggs'],
    'owner'
  ) RETURNING id
)
, ing AS (
  INSERT INTO public.ingredients (recipe_id, item, sort_order) VALUES
    ((SELECT id FROM new_recipe), '150g egg whites', 0),
    ((SELECT id FROM new_recipe), '80g mixed salad leaves', 1),
    ((SELECT id FROM new_recipe), '20g olives (pitted)', 2),
    ((SELECT id FROM new_recipe), '10g olive oil', 3),
    ((SELECT id FROM new_recipe), 'oregano, basil and a squeeze of lemon', 4),
    ((SELECT id FROM new_recipe), 'Salt and black pepper, to taste', 5)
  RETURNING 1
)
INSERT INTO public.steps (recipe_id, step_number, instruction) VALUES
    ((SELECT id FROM new_recipe), 1, 'Season the egg whites generously with oregano, basil and a squeeze of lemon.'),
    ((SELECT id FROM new_recipe), 2, 'Cook the egg whites scrambled until cooked through, turning once.'),
    ((SELECT id FROM new_recipe), 3, 'Wash and prepare the mixed salad leaves and olives, then set aside to serve fresh.'),
    ((SELECT id FROM new_recipe), 4, 'Plate the mixed salad leaves and olives, top with the egg whites.'),
    ((SELECT id FROM new_recipe), 5, 'Finish with the olive oil and a final crack of black pepper. Serve immediately.');

COMMIT;